"""
Template deployment — copy this as a starting point if you cannot use the
bootstrap tool, or to understand what fields are required. The bootstrap
(tools/bootstrap_deployment.py) is the recommended path: it resolves IDs from
ESI, walks the gate graph, and fills in everything except FRIENDLY_*/upgrades.

Activate a deployment by setting the DEPLOYMENT env var to the module name
(e.g. DEPLOYMENT=lawn_perrigen). The default is lawn_perrigen.
"""

# Stable identifier used to scope DB rows (ADM/activity history, timers,
# annotations, jump bridges) to this deployment. Changing it after rows
# have been written will hide that history.
DEPLOYMENT_ID = "example-deployment"

# Numeric IDs from ESI plus display strings used throughout the UI.
# Look these up with `python tools/esi_lookup.py alliance "..."`.
ALLIANCE = {
    "id": 0,
    "name": "Example Alliance",
    "ticker": "EXAM",
    "short_name": "EXAM",          # used in notification text
    "display_name": "EXAMPLE ALLIANCE",  # used in dashboard header
}

# Region this deployment monitors. Used to scope zKillboard region feeds and
# to discover constellations/systems via /universe/regions/<id>.
REGION = {
    "id": 0,
    "name": "Example Region",
}

# Constellations this alliance holds sov in. SystemState marks systems in these
# constellations as `is_primary` so the UI highlights them. Other constellations
# in the region are still loaded for context but rendered dimly.
PRIMARY_CONSTELLATION_IDS = []
PRIMARY_CONSTELLATION_NAMES = []

# IDs and names of allied alliances/corps. Used by sov_routes and intel_routes
# to classify holders as friendly vs hostile.
FRIENDLY_ALLIANCE_IDS = []
FRIENDLY_ALLIANCES = []          # display names (parallel list; both shown in UI)
FRIENDLY_CORPORATIONS = []

# Threat alliances tracked by the Neighbor Threat Profiling panel.
NEIGHBOR_ENTITIES = [
    # {"name": "Some Hostile Alliance", "id": 99000000, "type": "alliance"},
]

# Systems just outside the primary region that share a gate with one of our
# systems. Resolved at startup so the early-warning panel can include them.
NEIGHBOR_SYSTEM_NAMES = []

# Convenience lists of system names. PRIMARY_SYSTEMS is sov space; BORDER_SYSTEMS
# is primary-region systems with at least one gate leading outside the primary
# constellations (entry points).
PRIMARY_SYSTEMS = []
BORDER_SYSTEMS = []

# Per-system iHub upgrades. Manually maintained — ESI does not expose iHub
# fittings without SSO. Keys must match system names from PRIMARY_SYSTEMS.
# Upgrade type abbreviations come from eve_constants.UPGRADE_TYPES.
SYSTEM_UPGRADES = {
    # "EXAM-1": [{"type": "MTD", "level": 3}, {"type": "PA_Trit", "level": 1}],
}

# Map layout — each entry: {x, y, constellation, lawn?, security?, note?}.
# `lawn: True` marks primary-constellation systems for emphasis. `note` is the
# region name for neighbor systems (shown in tooltips).
MAP_LAYOUT = {
    # "EXAM-1": {"x": 500, "y": 250, "constellation": "EXAM-A", "lawn": True},
}

# Subway-style abstract layout. Often identical to MAP_LAYOUT initially; tune
# separately for the alternate map mode.
MAP_LAYOUT_SUBWAY = {}

# Gate connections. Type is one of:
#   internal — same constellation
#   cross    — different constellations, same region
#   regional — primary region <-> neighbor region
#   neighbor — between two neighbor-region systems
MAP_CONNECTIONS = [
    # ["EXAM-1", "EXAM-2", "internal"],
]

# Planetary interaction data per primary system. Auto-generated by bootstrap.
# Each planet: {planet_id, name, type_id, type}.
PI_DATA = {
    # "EXAM-1": [{"planet_id": 40000000, "name": "EXAM-1 I", "type_id": 11, "type": "Planet (Temperate)"}],
}
