"""
Deployment: lawn-perrigen
Auto-generated by tools/bootstrap_deployment.py at 2026-05-05T03:16:04Z
Region: Perrigen Falls (10000066)
Primary constellations: 9BGY-6, WXB-RY

Re-run the bootstrap to refresh region geography, gate connections, and PI
data. The MAP_LAYOUT and MAP_LAYOUT_SUBWAY positions are starter values from
an automatic layout — hand-tune them for readability, then keep them in
source control. SYSTEM_UPGRADES is intentionally empty: populate it as
upgrades are installed in-game.
"""

DEPLOYMENT_ID = 'lawn-perrigen'

ALLIANCE = {
    "id": 150097440,
    "name": "Get Off My Lawn",
    "ticker": "LAWN",
    "short_name": "LAWN",
    "display_name": "GET OFF MY LAWN"
}

REGION = {
    "id": 10000066,
    "name": "Perrigen Falls"
}

PRIMARY_CONSTELLATION_IDS = [
    20000748,
    20000755
]
PRIMARY_CONSTELLATION_NAMES = [
    "9BGY-6",
    "WXB-RY"
]

# ===== Friendlies and threat tracking (manually maintained) =====
# Copy these from your previous deployment when migrating, or fill in fresh.
FRIENDLY_ALLIANCE_IDS = [
    99012845,
    99013982,
    99008788,
    99010468,
    99012018
]

FRIENDLY_ALLIANCES = [
    "Get Off My Lawn",
    "BorderZone",
    "Gnomes Rising HoA",
    "The Skeleton Crew",
    "Weapons Of Mass Production.",
    "EDENCOM DEFENSIVE INITIATIVE"
]

FRIENDLY_CORPORATIONS = [
    "Astrum Mechanica",
    "DarkMatterEnterprises",
    "Derp Company",
    "Dormir no da ISK",
    "Gnome Tactical Foundations and Orientation",
    "Gnomeland Services",
    "Gnomes von Zurich",
    "Gnomestead Structures",
    "LAWN HC",
    "Moo-Tang Clan",
    "Obsidian Engineering",
    "Undersized Armada"
]

NEIGHBOR_ENTITIES = [
    {
        "name": "Deepwater Hooligans",
        "id": 99009927,
        "type": "alliance"
    },
    {
        "name": "PUT THE FRIES IN THE BAG",
        "id": 99014518,
        "type": "alliance"
    },
    {
        "name": "The Rejected.",
        "id": 99014523,
        "type": "alliance"
    }
]

# ===== Region geography (auto-generated) =====
# Systems just outside the primary region that share a gate with one of our
# systems. Used by SystemState.resolve_all_systems for the early-warning panel.
NEIGHBOR_SYSTEM_NAMES = [
    "9S-GPT",
    "DYS-CG",
    "EU-WFW",
    "HD-JVQ",
    "IF-KD1",
    "L-EUY2",
    "MTGF-2",
    "O8W-5O",
    "OTJ9-E",
    "QCGG-Q",
    "QE2-FS",
    "QZ1-OH",
    "Y-0HVF",
    "Z-DRIY"
]

PRIMARY_SYSTEMS = [
    "3LL-O0",
    "49V-E4",
    "4F6-VZ",
    "5T-A3D",
    "5ZU-VG",
    "6-1T6Z",
    "6-8QLA",
    "8B-A4E",
    "A1F-22",
    "B-7LYC",
    "EH2I-P",
    "G-GRSZ",
    "HB-KSF",
    "J9A-BH",
    "JM0A-4",
    "L-POLO",
    "LW-YEW",
    "OP7-BP",
    "PT-2KR",
    "R-AYGT"
]

BORDER_SYSTEMS = [
    "5T-A3D",
    "5ZU-VG",
    "6-1T6Z",
    "J9A-BH",
    "LW-YEW"
]

# ===== Sov upgrades (manual — populate as upgrades are installed) =====
SYSTEM_UPGRADES = {}

# ===== Map layout (auto-generated, hand-tune for readability) =====
MAP_LAYOUT = {
    "5T-A3D": {
        "x": 218,
        "y": 89,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "5ZU-VG": {
        "x": 248,
        "y": 99,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "6-1T6Z": {
        "x": 267,
        "y": 125,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "6-8QLA": {
        "x": 267,
        "y": 157,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "EH2I-P": {
        "x": 248,
        "y": 183,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "G-GRSZ": {
        "x": 218,
        "y": 193,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "HB-KSF": {
        "x": 187,
        "y": 183,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "LW-YEW": {
        "x": 168,
        "y": 157,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "OP7-BP": {
        "x": 168,
        "y": 125,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "R-AYGT": {
        "x": 187,
        "y": 99,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "3LL-O0": {
        "x": 492,
        "y": 89,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "49V-E4": {
        "x": 523,
        "y": 99,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "4F6-VZ": {
        "x": 542,
        "y": 125,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "8B-A4E": {
        "x": 542,
        "y": 157,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "A1F-22": {
        "x": 523,
        "y": 183,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "B-7LYC": {
        "x": 492,
        "y": 193,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "J9A-BH": {
        "x": 462,
        "y": 183,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "JM0A-4": {
        "x": 443,
        "y": 157,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "L-POLO": {
        "x": 443,
        "y": 125,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "PT-2KR": {
        "x": 462,
        "y": 99,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "6Q4-X6": {
        "x": 768,
        "y": 89,
        "constellation": "4LEZ-6"
    },
    "B9N2-2": {
        "x": 813,
        "y": 115,
        "constellation": "4LEZ-6"
    },
    "D-QJR9": {
        "x": 813,
        "y": 167,
        "constellation": "4LEZ-6"
    },
    "H-29TM": {
        "x": 768,
        "y": 193,
        "constellation": "4LEZ-6"
    },
    "KOI8-Z": {
        "x": 722,
        "y": 167,
        "constellation": "4LEZ-6"
    },
    "U4-V3J": {
        "x": 722,
        "y": 115,
        "constellation": "4LEZ-6"
    },
    "0FG-KS": {
        "x": 1042,
        "y": 89,
        "constellation": "B-MQ0Y"
    },
    "E-WMT7": {
        "x": 1088,
        "y": 115,
        "constellation": "B-MQ0Y"
    },
    "EF-QZK": {
        "x": 1088,
        "y": 167,
        "constellation": "B-MQ0Y"
    },
    "F-5WYK": {
        "x": 1042,
        "y": 193,
        "constellation": "B-MQ0Y"
    },
    "FLK-LJ": {
        "x": 997,
        "y": 167,
        "constellation": "B-MQ0Y"
    },
    "RZ3O-K": {
        "x": 997,
        "y": 115,
        "constellation": "B-MQ0Y"
    },
    "2-YO2K": {
        "x": 218,
        "y": 252,
        "constellation": "BXT7-V"
    },
    "M-SG47": {
        "x": 263,
        "y": 278,
        "constellation": "BXT7-V"
    },
    "QHY-RU": {
        "x": 263,
        "y": 330,
        "constellation": "BXT7-V"
    },
    "SR-10Z": {
        "x": 218,
        "y": 356,
        "constellation": "BXT7-V"
    },
    "TAL1-3": {
        "x": 172,
        "y": 330,
        "constellation": "BXT7-V"
    },
    "W-KXEX": {
        "x": 172,
        "y": 278,
        "constellation": "BXT7-V"
    },
    "4-1ECP": {
        "x": 492,
        "y": 252,
        "constellation": "L7-RDZ"
    },
    "5-U12M": {
        "x": 533,
        "y": 271,
        "constellation": "L7-RDZ"
    },
    "7AH-SF": {
        "x": 543,
        "y": 315,
        "constellation": "L7-RDZ"
    },
    "7MMJ-3": {
        "x": 515,
        "y": 351,
        "constellation": "L7-RDZ"
    },
    "9-EXU9": {
        "x": 470,
        "y": 351,
        "constellation": "L7-RDZ"
    },
    "PVF-N9": {
        "x": 442,
        "y": 315,
        "constellation": "L7-RDZ"
    },
    "UYOC-1": {
        "x": 452,
        "y": 271,
        "constellation": "L7-RDZ"
    },
    "7JRA-G": {
        "x": 768,
        "y": 252,
        "constellation": "LWMW-6"
    },
    "L5Y4-M": {
        "x": 813,
        "y": 278,
        "constellation": "LWMW-6"
    },
    "PFV-ZH": {
        "x": 813,
        "y": 330,
        "constellation": "LWMW-6"
    },
    "SY-OLX": {
        "x": 768,
        "y": 356,
        "constellation": "LWMW-6"
    },
    "W-CSFY": {
        "x": 722,
        "y": 330,
        "constellation": "LWMW-6"
    },
    "XY-ZCI": {
        "x": 722,
        "y": 278,
        "constellation": "LWMW-6"
    },
    "A9-F18": {
        "x": 1042,
        "y": 252,
        "constellation": "NT1-5Q"
    },
    "B-B0ME": {
        "x": 1088,
        "y": 278,
        "constellation": "NT1-5Q"
    },
    "DE-IHK": {
        "x": 1088,
        "y": 330,
        "constellation": "NT1-5Q"
    },
    "H-HGGJ": {
        "x": 1042,
        "y": 356,
        "constellation": "NT1-5Q"
    },
    "OJT-J3": {
        "x": 997,
        "y": 330,
        "constellation": "NT1-5Q"
    },
    "TDP-T3": {
        "x": 997,
        "y": 278,
        "constellation": "NT1-5Q"
    },
    "2V-ZHM": {
        "x": 218,
        "y": 414,
        "constellation": "O5PO-O"
    },
    "AK-L0Z": {
        "x": 263,
        "y": 440,
        "constellation": "O5PO-O"
    },
    "AY9X-Q": {
        "x": 263,
        "y": 492,
        "constellation": "O5PO-O"
    },
    "R-AG7W": {
        "x": 218,
        "y": 518,
        "constellation": "O5PO-O"
    },
    "V-3K7C": {
        "x": 172,
        "y": 492,
        "constellation": "O5PO-O"
    },
    "XU7-CH": {
        "x": 172,
        "y": 440,
        "constellation": "O5PO-O"
    },
    "9-ZA4Z": {
        "x": 492,
        "y": 414,
        "constellation": "Q0-4FU"
    },
    "IU-E9T": {
        "x": 538,
        "y": 440,
        "constellation": "Q0-4FU"
    },
    "NGM-OK": {
        "x": 538,
        "y": 492,
        "constellation": "Q0-4FU"
    },
    "O-QKSM": {
        "x": 492,
        "y": 518,
        "constellation": "Q0-4FU"
    },
    "QKQ3-L": {
        "x": 447,
        "y": 492,
        "constellation": "Q0-4FU"
    },
    "VWES-Y": {
        "x": 447,
        "y": 440,
        "constellation": "Q0-4FU"
    },
    "2AUL-X": {
        "x": 768,
        "y": 414,
        "constellation": "S0X-O4"
    },
    "9IZ-HU": {
        "x": 813,
        "y": 440,
        "constellation": "S0X-O4"
    },
    "F-A3TR": {
        "x": 813,
        "y": 492,
        "constellation": "S0X-O4"
    },
    "F-HQWV": {
        "x": 768,
        "y": 518,
        "constellation": "S0X-O4"
    },
    "OBV-YC": {
        "x": 722,
        "y": 492,
        "constellation": "S0X-O4"
    },
    "PA-ALN": {
        "x": 722,
        "y": 440,
        "constellation": "S0X-O4"
    },
    "0-U2M4": {
        "x": 1042,
        "y": 414,
        "constellation": "TPB-KG"
    },
    "01B-88": {
        "x": 1088,
        "y": 440,
        "constellation": "TPB-KG"
    },
    "C3I-D5": {
        "x": 1088,
        "y": 492,
        "constellation": "TPB-KG"
    },
    "F18-AY": {
        "x": 1042,
        "y": 518,
        "constellation": "TPB-KG"
    },
    "MTO2-2": {
        "x": 997,
        "y": 492,
        "constellation": "TPB-KG"
    },
    "RZ8A-P": {
        "x": 997,
        "y": 440,
        "constellation": "TPB-KG"
    },
    "0XN-SK": {
        "x": 218,
        "y": 577,
        "constellation": "TY0-Q2"
    },
    "4F9Y-3": {
        "x": 263,
        "y": 603,
        "constellation": "TY0-Q2"
    },
    "5V-Q1R": {
        "x": 263,
        "y": 655,
        "constellation": "TY0-Q2"
    },
    "M4-KX5": {
        "x": 218,
        "y": 681,
        "constellation": "TY0-Q2"
    },
    "MS-RXH": {
        "x": 172,
        "y": 655,
        "constellation": "TY0-Q2"
    },
    "U-3FKL": {
        "x": 172,
        "y": 603,
        "constellation": "TY0-Q2"
    },
    "7M4-4C": {
        "x": 492,
        "y": 577,
        "constellation": "VT-LHB"
    },
    "972C-1": {
        "x": 523,
        "y": 587,
        "constellation": "VT-LHB"
    },
    "9WVY-F": {
        "x": 542,
        "y": 613,
        "constellation": "VT-LHB"
    },
    "BEG-RL": {
        "x": 542,
        "y": 645,
        "constellation": "VT-LHB"
    },
    "JPEZ-R": {
        "x": 523,
        "y": 671,
        "constellation": "VT-LHB"
    },
    "JZ-UQC": {
        "x": 492,
        "y": 681,
        "constellation": "VT-LHB"
    },
    "M5NO-B": {
        "x": 462,
        "y": 671,
        "constellation": "VT-LHB"
    },
    "MJ-5F9": {
        "x": 443,
        "y": 645,
        "constellation": "VT-LHB"
    },
    "U-W436": {
        "x": 443,
        "y": 613,
        "constellation": "VT-LHB"
    },
    "Z-ENUD": {
        "x": 462,
        "y": 587,
        "constellation": "VT-LHB"
    },
    "1A8-6G": {
        "x": 768,
        "y": 577,
        "constellation": "X7-FTR"
    },
    "4-M1TY": {
        "x": 808,
        "y": 596,
        "constellation": "X7-FTR"
    },
    "C6CG-W": {
        "x": 818,
        "y": 640,
        "constellation": "X7-FTR"
    },
    "H-FOYG": {
        "x": 790,
        "y": 676,
        "constellation": "X7-FTR"
    },
    "K-3PQW": {
        "x": 745,
        "y": 676,
        "constellation": "X7-FTR"
    },
    "PE-SAM": {
        "x": 717,
        "y": 640,
        "constellation": "X7-FTR"
    },
    "RY-2FX": {
        "x": 727,
        "y": 596,
        "constellation": "X7-FTR"
    },
    "Z-DRIY": {
        "x": 20,
        "y": 60,
        "constellation": "neighbor",
        "note": "Etherium Reach"
    },
    "IF-KD1": {
        "x": 200,
        "y": 10,
        "constellation": "neighbor",
        "note": "Malpais"
    },
    "O8W-5O": {
        "x": 260,
        "y": 10,
        "constellation": "neighbor",
        "note": "Malpais"
    },
    "QCGG-Q": {
        "x": 320,
        "y": 10,
        "constellation": "neighbor",
        "note": "Malpais"
    },
    "QZ1-OH": {
        "x": 380,
        "y": 10,
        "constellation": "neighbor",
        "note": "Malpais"
    },
    "DYS-CG": {
        "x": 1180,
        "y": 60,
        "constellation": "neighbor",
        "note": "Oasa"
    },
    "MTGF-2": {
        "x": 1180,
        "y": 100,
        "constellation": "neighbor",
        "note": "Oasa"
    },
    "QE2-FS": {
        "x": 1180,
        "y": 140,
        "constellation": "neighbor",
        "note": "Oasa"
    },
    "Y-0HVF": {
        "x": 1180,
        "y": 180,
        "constellation": "neighbor",
        "note": "Oasa"
    },
    "9S-GPT": {
        "x": 200,
        "y": 730,
        "constellation": "neighbor",
        "note": "Outer Passage"
    },
    "EU-WFW": {
        "x": 20,
        "y": 60,
        "constellation": "neighbor",
        "note": "The Spire"
    },
    "L-EUY2": {
        "x": 20,
        "y": 100,
        "constellation": "neighbor",
        "note": "The Spire"
    },
    "OTJ9-E": {
        "x": 20,
        "y": 140,
        "constellation": "neighbor",
        "note": "The Spire"
    },
    "HD-JVQ": {
        "x": 200,
        "y": 10,
        "constellation": "neighbor",
        "note": "Venal"
    }
}

# Subway-style layout: starts identical to MAP_LAYOUT. Adjust to taste; the
# subway view prioritises readability (orthogonal angles, generous spacing)
# over geometric accuracy.
MAP_LAYOUT_SUBWAY = {
    "5T-A3D": {
        "x": 218,
        "y": 89,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "5ZU-VG": {
        "x": 248,
        "y": 99,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "6-1T6Z": {
        "x": 267,
        "y": 125,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "6-8QLA": {
        "x": 267,
        "y": 157,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "EH2I-P": {
        "x": 248,
        "y": 183,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "G-GRSZ": {
        "x": 218,
        "y": 193,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "HB-KSF": {
        "x": 187,
        "y": 183,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "LW-YEW": {
        "x": 168,
        "y": 157,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "OP7-BP": {
        "x": 168,
        "y": 125,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "R-AYGT": {
        "x": 187,
        "y": 99,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "3LL-O0": {
        "x": 492,
        "y": 89,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "49V-E4": {
        "x": 523,
        "y": 99,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "4F6-VZ": {
        "x": 542,
        "y": 125,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "8B-A4E": {
        "x": 542,
        "y": 157,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "A1F-22": {
        "x": 523,
        "y": 183,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "B-7LYC": {
        "x": 492,
        "y": 193,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "J9A-BH": {
        "x": 462,
        "y": 183,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "JM0A-4": {
        "x": 443,
        "y": 157,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "L-POLO": {
        "x": 443,
        "y": 125,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "PT-2KR": {
        "x": 462,
        "y": 99,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "6Q4-X6": {
        "x": 768,
        "y": 89,
        "constellation": "4LEZ-6"
    },
    "B9N2-2": {
        "x": 813,
        "y": 115,
        "constellation": "4LEZ-6"
    },
    "D-QJR9": {
        "x": 813,
        "y": 167,
        "constellation": "4LEZ-6"
    },
    "H-29TM": {
        "x": 768,
        "y": 193,
        "constellation": "4LEZ-6"
    },
    "KOI8-Z": {
        "x": 722,
        "y": 167,
        "constellation": "4LEZ-6"
    },
    "U4-V3J": {
        "x": 722,
        "y": 115,
        "constellation": "4LEZ-6"
    },
    "0FG-KS": {
        "x": 1042,
        "y": 89,
        "constellation": "B-MQ0Y"
    },
    "E-WMT7": {
        "x": 1088,
        "y": 115,
        "constellation": "B-MQ0Y"
    },
    "EF-QZK": {
        "x": 1088,
        "y": 167,
        "constellation": "B-MQ0Y"
    },
    "F-5WYK": {
        "x": 1042,
        "y": 193,
        "constellation": "B-MQ0Y"
    },
    "FLK-LJ": {
        "x": 997,
        "y": 167,
        "constellation": "B-MQ0Y"
    },
    "RZ3O-K": {
        "x": 997,
        "y": 115,
        "constellation": "B-MQ0Y"
    },
    "2-YO2K": {
        "x": 218,
        "y": 252,
        "constellation": "BXT7-V"
    },
    "M-SG47": {
        "x": 263,
        "y": 278,
        "constellation": "BXT7-V"
    },
    "QHY-RU": {
        "x": 263,
        "y": 330,
        "constellation": "BXT7-V"
    },
    "SR-10Z": {
        "x": 218,
        "y": 356,
        "constellation": "BXT7-V"
    },
    "TAL1-3": {
        "x": 172,
        "y": 330,
        "constellation": "BXT7-V"
    },
    "W-KXEX": {
        "x": 172,
        "y": 278,
        "constellation": "BXT7-V"
    },
    "4-1ECP": {
        "x": 492,
        "y": 252,
        "constellation": "L7-RDZ"
    },
    "5-U12M": {
        "x": 533,
        "y": 271,
        "constellation": "L7-RDZ"
    },
    "7AH-SF": {
        "x": 543,
        "y": 315,
        "constellation": "L7-RDZ"
    },
    "7MMJ-3": {
        "x": 515,
        "y": 351,
        "constellation": "L7-RDZ"
    },
    "9-EXU9": {
        "x": 470,
        "y": 351,
        "constellation": "L7-RDZ"
    },
    "PVF-N9": {
        "x": 442,
        "y": 315,
        "constellation": "L7-RDZ"
    },
    "UYOC-1": {
        "x": 452,
        "y": 271,
        "constellation": "L7-RDZ"
    },
    "7JRA-G": {
        "x": 768,
        "y": 252,
        "constellation": "LWMW-6"
    },
    "L5Y4-M": {
        "x": 813,
        "y": 278,
        "constellation": "LWMW-6"
    },
    "PFV-ZH": {
        "x": 813,
        "y": 330,
        "constellation": "LWMW-6"
    },
    "SY-OLX": {
        "x": 768,
        "y": 356,
        "constellation": "LWMW-6"
    },
    "W-CSFY": {
        "x": 722,
        "y": 330,
        "constellation": "LWMW-6"
    },
    "XY-ZCI": {
        "x": 722,
        "y": 278,
        "constellation": "LWMW-6"
    },
    "A9-F18": {
        "x": 1042,
        "y": 252,
        "constellation": "NT1-5Q"
    },
    "B-B0ME": {
        "x": 1088,
        "y": 278,
        "constellation": "NT1-5Q"
    },
    "DE-IHK": {
        "x": 1088,
        "y": 330,
        "constellation": "NT1-5Q"
    },
    "H-HGGJ": {
        "x": 1042,
        "y": 356,
        "constellation": "NT1-5Q"
    },
    "OJT-J3": {
        "x": 997,
        "y": 330,
        "constellation": "NT1-5Q"
    },
    "TDP-T3": {
        "x": 997,
        "y": 278,
        "constellation": "NT1-5Q"
    },
    "2V-ZHM": {
        "x": 218,
        "y": 414,
        "constellation": "O5PO-O"
    },
    "AK-L0Z": {
        "x": 263,
        "y": 440,
        "constellation": "O5PO-O"
    },
    "AY9X-Q": {
        "x": 263,
        "y": 492,
        "constellation": "O5PO-O"
    },
    "R-AG7W": {
        "x": 218,
        "y": 518,
        "constellation": "O5PO-O"
    },
    "V-3K7C": {
        "x": 172,
        "y": 492,
        "constellation": "O5PO-O"
    },
    "XU7-CH": {
        "x": 172,
        "y": 440,
        "constellation": "O5PO-O"
    },
    "9-ZA4Z": {
        "x": 492,
        "y": 414,
        "constellation": "Q0-4FU"
    },
    "IU-E9T": {
        "x": 538,
        "y": 440,
        "constellation": "Q0-4FU"
    },
    "NGM-OK": {
        "x": 538,
        "y": 492,
        "constellation": "Q0-4FU"
    },
    "O-QKSM": {
        "x": 492,
        "y": 518,
        "constellation": "Q0-4FU"
    },
    "QKQ3-L": {
        "x": 447,
        "y": 492,
        "constellation": "Q0-4FU"
    },
    "VWES-Y": {
        "x": 447,
        "y": 440,
        "constellation": "Q0-4FU"
    },
    "2AUL-X": {
        "x": 768,
        "y": 414,
        "constellation": "S0X-O4"
    },
    "9IZ-HU": {
        "x": 813,
        "y": 440,
        "constellation": "S0X-O4"
    },
    "F-A3TR": {
        "x": 813,
        "y": 492,
        "constellation": "S0X-O4"
    },
    "F-HQWV": {
        "x": 768,
        "y": 518,
        "constellation": "S0X-O4"
    },
    "OBV-YC": {
        "x": 722,
        "y": 492,
        "constellation": "S0X-O4"
    },
    "PA-ALN": {
        "x": 722,
        "y": 440,
        "constellation": "S0X-O4"
    },
    "0-U2M4": {
        "x": 1042,
        "y": 414,
        "constellation": "TPB-KG"
    },
    "01B-88": {
        "x": 1088,
        "y": 440,
        "constellation": "TPB-KG"
    },
    "C3I-D5": {
        "x": 1088,
        "y": 492,
        "constellation": "TPB-KG"
    },
    "F18-AY": {
        "x": 1042,
        "y": 518,
        "constellation": "TPB-KG"
    },
    "MTO2-2": {
        "x": 997,
        "y": 492,
        "constellation": "TPB-KG"
    },
    "RZ8A-P": {
        "x": 997,
        "y": 440,
        "constellation": "TPB-KG"
    },
    "0XN-SK": {
        "x": 218,
        "y": 577,
        "constellation": "TY0-Q2"
    },
    "4F9Y-3": {
        "x": 263,
        "y": 603,
        "constellation": "TY0-Q2"
    },
    "5V-Q1R": {
        "x": 263,
        "y": 655,
        "constellation": "TY0-Q2"
    },
    "M4-KX5": {
        "x": 218,
        "y": 681,
        "constellation": "TY0-Q2"
    },
    "MS-RXH": {
        "x": 172,
        "y": 655,
        "constellation": "TY0-Q2"
    },
    "U-3FKL": {
        "x": 172,
        "y": 603,
        "constellation": "TY0-Q2"
    },
    "7M4-4C": {
        "x": 492,
        "y": 577,
        "constellation": "VT-LHB"
    },
    "972C-1": {
        "x": 523,
        "y": 587,
        "constellation": "VT-LHB"
    },
    "9WVY-F": {
        "x": 542,
        "y": 613,
        "constellation": "VT-LHB"
    },
    "BEG-RL": {
        "x": 542,
        "y": 645,
        "constellation": "VT-LHB"
    },
    "JPEZ-R": {
        "x": 523,
        "y": 671,
        "constellation": "VT-LHB"
    },
    "JZ-UQC": {
        "x": 492,
        "y": 681,
        "constellation": "VT-LHB"
    },
    "M5NO-B": {
        "x": 462,
        "y": 671,
        "constellation": "VT-LHB"
    },
    "MJ-5F9": {
        "x": 443,
        "y": 645,
        "constellation": "VT-LHB"
    },
    "U-W436": {
        "x": 443,
        "y": 613,
        "constellation": "VT-LHB"
    },
    "Z-ENUD": {
        "x": 462,
        "y": 587,
        "constellation": "VT-LHB"
    },
    "1A8-6G": {
        "x": 768,
        "y": 577,
        "constellation": "X7-FTR"
    },
    "4-M1TY": {
        "x": 808,
        "y": 596,
        "constellation": "X7-FTR"
    },
    "C6CG-W": {
        "x": 818,
        "y": 640,
        "constellation": "X7-FTR"
    },
    "H-FOYG": {
        "x": 790,
        "y": 676,
        "constellation": "X7-FTR"
    },
    "K-3PQW": {
        "x": 745,
        "y": 676,
        "constellation": "X7-FTR"
    },
    "PE-SAM": {
        "x": 717,
        "y": 640,
        "constellation": "X7-FTR"
    },
    "RY-2FX": {
        "x": 727,
        "y": 596,
        "constellation": "X7-FTR"
    },
    "Z-DRIY": {
        "x": 20,
        "y": 60,
        "constellation": "neighbor",
        "note": "Etherium Reach"
    },
    "IF-KD1": {
        "x": 200,
        "y": 10,
        "constellation": "neighbor",
        "note": "Malpais"
    },
    "O8W-5O": {
        "x": 260,
        "y": 10,
        "constellation": "neighbor",
        "note": "Malpais"
    },
    "QCGG-Q": {
        "x": 320,
        "y": 10,
        "constellation": "neighbor",
        "note": "Malpais"
    },
    "QZ1-OH": {
        "x": 380,
        "y": 10,
        "constellation": "neighbor",
        "note": "Malpais"
    },
    "DYS-CG": {
        "x": 1180,
        "y": 60,
        "constellation": "neighbor",
        "note": "Oasa"
    },
    "MTGF-2": {
        "x": 1180,
        "y": 100,
        "constellation": "neighbor",
        "note": "Oasa"
    },
    "QE2-FS": {
        "x": 1180,
        "y": 140,
        "constellation": "neighbor",
        "note": "Oasa"
    },
    "Y-0HVF": {
        "x": 1180,
        "y": 180,
        "constellation": "neighbor",
        "note": "Oasa"
    },
    "9S-GPT": {
        "x": 200,
        "y": 730,
        "constellation": "neighbor",
        "note": "Outer Passage"
    },
    "EU-WFW": {
        "x": 20,
        "y": 60,
        "constellation": "neighbor",
        "note": "The Spire"
    },
    "L-EUY2": {
        "x": 20,
        "y": 100,
        "constellation": "neighbor",
        "note": "The Spire"
    },
    "OTJ9-E": {
        "x": 20,
        "y": 140,
        "constellation": "neighbor",
        "note": "The Spire"
    },
    "HD-JVQ": {
        "x": 200,
        "y": 10,
        "constellation": "neighbor",
        "note": "Venal"
    }
}

MAP_CONNECTIONS = [
    [
        "1A8-6G",
        "2V-ZHM",
        "cross"
    ],
    [
        "5-U12M",
        "01B-88",
        "cross"
    ],
    [
        "5ZU-VG",
        "H-29TM",
        "cross"
    ],
    [
        "6-1T6Z",
        "7AH-SF",
        "cross"
    ],
    [
        "9IZ-HU",
        "9-ZA4Z",
        "cross"
    ],
    [
        "AK-L0Z",
        "2-YO2K",
        "cross"
    ],
    [
        "AK-L0Z",
        "H-FOYG",
        "cross"
    ],
    [
        "C6CG-W",
        "5V-Q1R",
        "cross"
    ],
    [
        "DE-IHK",
        "LW-YEW",
        "cross"
    ],
    [
        "H-FOYG",
        "2V-ZHM",
        "cross"
    ],
    [
        "H-FOYG",
        "A9-F18",
        "cross"
    ],
    [
        "OP7-BP",
        "B-7LYC",
        "cross"
    ],
    [
        "RZ3O-K",
        "0XN-SK",
        "cross"
    ],
    [
        "RZ3O-K",
        "4F9Y-3",
        "cross"
    ],
    [
        "TDP-T3",
        "MJ-5F9",
        "cross"
    ],
    [
        "U-3FKL",
        "9-ZA4Z",
        "cross"
    ],
    [
        "U-3FKL",
        "SY-OLX",
        "cross"
    ],
    [
        "XU7-CH",
        "H-HGGJ",
        "cross"
    ],
    [
        "01B-88",
        "0-U2M4",
        "internal"
    ],
    [
        "01B-88",
        "F18-AY",
        "internal"
    ],
    [
        "0FG-KS",
        "F-5WYK",
        "internal"
    ],
    [
        "0FG-KS",
        "RZ3O-K",
        "internal"
    ],
    [
        "1A8-6G",
        "PE-SAM",
        "internal"
    ],
    [
        "1A8-6G",
        "RY-2FX",
        "internal"
    ],
    [
        "2AUL-X",
        "PA-ALN",
        "internal"
    ],
    [
        "4-1ECP",
        "5-U12M",
        "internal"
    ],
    [
        "4-1ECP",
        "UYOC-1",
        "internal"
    ],
    [
        "4-M1TY",
        "K-3PQW",
        "internal"
    ],
    [
        "4F6-VZ",
        "3LL-O0",
        "internal"
    ],
    [
        "4F6-VZ",
        "L-POLO",
        "internal"
    ],
    [
        "4F9Y-3",
        "0XN-SK",
        "internal"
    ],
    [
        "5T-A3D",
        "5ZU-VG",
        "internal"
    ],
    [
        "5V-Q1R",
        "0XN-SK",
        "internal"
    ],
    [
        "5V-Q1R",
        "4F9Y-3",
        "internal"
    ],
    [
        "5V-Q1R",
        "MS-RXH",
        "internal"
    ],
    [
        "6-1T6Z",
        "5ZU-VG",
        "internal"
    ],
    [
        "6Q4-X6",
        "B9N2-2",
        "internal"
    ],
    [
        "6Q4-X6",
        "U4-V3J",
        "internal"
    ],
    [
        "7AH-SF",
        "4-1ECP",
        "internal"
    ],
    [
        "7AH-SF",
        "5-U12M",
        "internal"
    ],
    [
        "7AH-SF",
        "7MMJ-3",
        "internal"
    ],
    [
        "7AH-SF",
        "9-EXU9",
        "internal"
    ],
    [
        "7AH-SF",
        "UYOC-1",
        "internal"
    ],
    [
        "7JRA-G",
        "W-CSFY",
        "internal"
    ],
    [
        "7MMJ-3",
        "5-U12M",
        "internal"
    ],
    [
        "7MMJ-3",
        "9-EXU9",
        "internal"
    ],
    [
        "7MMJ-3",
        "PVF-N9",
        "internal"
    ],
    [
        "8B-A4E",
        "L-POLO",
        "internal"
    ],
    [
        "9-EXU9",
        "4-1ECP",
        "internal"
    ],
    [
        "9-EXU9",
        "PVF-N9",
        "internal"
    ],
    [
        "9-ZA4Z",
        "IU-E9T",
        "internal"
    ],
    [
        "9-ZA4Z",
        "NGM-OK",
        "internal"
    ],
    [
        "972C-1",
        "BEG-RL",
        "internal"
    ],
    [
        "972C-1",
        "U-W436",
        "internal"
    ],
    [
        "9IZ-HU",
        "2AUL-X",
        "internal"
    ],
    [
        "9IZ-HU",
        "F-HQWV",
        "internal"
    ],
    [
        "9IZ-HU",
        "OBV-YC",
        "internal"
    ],
    [
        "9WVY-F",
        "JZ-UQC",
        "internal"
    ],
    [
        "A1F-22",
        "3LL-O0",
        "internal"
    ],
    [
        "AK-L0Z",
        "2V-ZHM",
        "internal"
    ],
    [
        "B-7LYC",
        "49V-E4",
        "internal"
    ],
    [
        "B-7LYC",
        "PT-2KR",
        "internal"
    ],
    [
        "B-B0ME",
        "H-HGGJ",
        "internal"
    ],
    [
        "BEG-RL",
        "Z-ENUD",
        "internal"
    ],
    [
        "C6CG-W",
        "PE-SAM",
        "internal"
    ],
    [
        "D-QJR9",
        "B9N2-2",
        "internal"
    ],
    [
        "E-WMT7",
        "F-5WYK",
        "internal"
    ],
    [
        "E-WMT7",
        "FLK-LJ",
        "internal"
    ],
    [
        "EF-QZK",
        "F-5WYK",
        "internal"
    ],
    [
        "EH2I-P",
        "6-8QLA",
        "internal"
    ],
    [
        "EH2I-P",
        "R-AYGT",
        "internal"
    ],
    [
        "F-A3TR",
        "9IZ-HU",
        "internal"
    ],
    [
        "F-A3TR",
        "F-HQWV",
        "internal"
    ],
    [
        "F-A3TR",
        "OBV-YC",
        "internal"
    ],
    [
        "F18-AY",
        "RZ8A-P",
        "internal"
    ],
    [
        "FLK-LJ",
        "0FG-KS",
        "internal"
    ],
    [
        "G-GRSZ",
        "R-AYGT",
        "internal"
    ],
    [
        "H-29TM",
        "D-QJR9",
        "internal"
    ],
    [
        "H-FOYG",
        "1A8-6G",
        "internal"
    ],
    [
        "H-HGGJ",
        "A9-F18",
        "internal"
    ],
    [
        "HB-KSF",
        "6-1T6Z",
        "internal"
    ],
    [
        "IU-E9T",
        "O-QKSM",
        "internal"
    ],
    [
        "J9A-BH",
        "4F6-VZ",
        "internal"
    ],
    [
        "J9A-BH",
        "B-7LYC",
        "internal"
    ],
    [
        "J9A-BH",
        "PT-2KR",
        "internal"
    ],
    [
        "JM0A-4",
        "3LL-O0",
        "internal"
    ],
    [
        "JM0A-4",
        "4F6-VZ",
        "internal"
    ],
    [
        "JM0A-4",
        "A1F-22",
        "internal"
    ],
    [
        "JZ-UQC",
        "7M4-4C",
        "internal"
    ],
    [
        "K-3PQW",
        "C6CG-W",
        "internal"
    ],
    [
        "K-3PQW",
        "PE-SAM",
        "internal"
    ],
    [
        "K-3PQW",
        "RY-2FX",
        "internal"
    ],
    [
        "KOI8-Z",
        "D-QJR9",
        "internal"
    ],
    [
        "KOI8-Z",
        "H-29TM",
        "internal"
    ],
    [
        "LW-YEW",
        "5T-A3D",
        "internal"
    ],
    [
        "LW-YEW",
        "6-8QLA",
        "internal"
    ],
    [
        "LW-YEW",
        "EH2I-P",
        "internal"
    ],
    [
        "LW-YEW",
        "HB-KSF",
        "internal"
    ],
    [
        "M-SG47",
        "2-YO2K",
        "internal"
    ],
    [
        "M-SG47",
        "W-KXEX",
        "internal"
    ],
    [
        "M4-KX5",
        "0XN-SK",
        "internal"
    ],
    [
        "M4-KX5",
        "5V-Q1R",
        "internal"
    ],
    [
        "M5NO-B",
        "7M4-4C",
        "internal"
    ],
    [
        "M5NO-B",
        "JPEZ-R",
        "internal"
    ],
    [
        "MS-RXH",
        "U-3FKL",
        "internal"
    ],
    [
        "MTO2-2",
        "RZ8A-P",
        "internal"
    ],
    [
        "NGM-OK",
        "IU-E9T",
        "internal"
    ],
    [
        "NGM-OK",
        "O-QKSM",
        "internal"
    ],
    [
        "O-QKSM",
        "QKQ3-L",
        "internal"
    ],
    [
        "OBV-YC",
        "2AUL-X",
        "internal"
    ],
    [
        "OBV-YC",
        "F-HQWV",
        "internal"
    ],
    [
        "OJT-J3",
        "DE-IHK",
        "internal"
    ],
    [
        "OP7-BP",
        "5ZU-VG",
        "internal"
    ],
    [
        "OP7-BP",
        "EH2I-P",
        "internal"
    ],
    [
        "PFV-ZH",
        "L5Y4-M",
        "internal"
    ],
    [
        "PFV-ZH",
        "W-CSFY",
        "internal"
    ],
    [
        "PVF-N9",
        "5-U12M",
        "internal"
    ],
    [
        "QHY-RU",
        "2-YO2K",
        "internal"
    ],
    [
        "R-AG7W",
        "AY9X-Q",
        "internal"
    ],
    [
        "R-AG7W",
        "XU7-CH",
        "internal"
    ],
    [
        "RZ8A-P",
        "0-U2M4",
        "internal"
    ],
    [
        "RZ8A-P",
        "C3I-D5",
        "internal"
    ],
    [
        "SR-10Z",
        "2-YO2K",
        "internal"
    ],
    [
        "SR-10Z",
        "M-SG47",
        "internal"
    ],
    [
        "SR-10Z",
        "QHY-RU",
        "internal"
    ],
    [
        "SY-OLX",
        "7JRA-G",
        "internal"
    ],
    [
        "SY-OLX",
        "W-CSFY",
        "internal"
    ],
    [
        "SY-OLX",
        "XY-ZCI",
        "internal"
    ],
    [
        "TAL1-3",
        "2-YO2K",
        "internal"
    ],
    [
        "TAL1-3",
        "M-SG47",
        "internal"
    ],
    [
        "TAL1-3",
        "QHY-RU",
        "internal"
    ],
    [
        "TDP-T3",
        "B-B0ME",
        "internal"
    ],
    [
        "TDP-T3",
        "OJT-J3",
        "internal"
    ],
    [
        "U-3FKL",
        "4F9Y-3",
        "internal"
    ],
    [
        "U-W436",
        "JZ-UQC",
        "internal"
    ],
    [
        "U4-V3J",
        "H-29TM",
        "internal"
    ],
    [
        "V-3K7C",
        "2V-ZHM",
        "internal"
    ],
    [
        "VWES-Y",
        "QKQ3-L",
        "internal"
    ],
    [
        "XU7-CH",
        "2V-ZHM",
        "internal"
    ],
    [
        "XU7-CH",
        "AY9X-Q",
        "internal"
    ],
    [
        "Z-ENUD",
        "M5NO-B",
        "internal"
    ],
    [
        "Z-ENUD",
        "MJ-5F9",
        "internal"
    ],
    [
        "Z-ENUD",
        "U-W436",
        "internal"
    ],
    [
        "5T-A3D",
        "MTGF-2",
        "regional"
    ],
    [
        "AY9X-Q",
        "O8W-5O",
        "regional"
    ],
    [
        "B-B0ME",
        "QCGG-Q",
        "regional"
    ],
    [
        "BEG-RL",
        "Z-DRIY",
        "regional"
    ],
    [
        "C3I-D5",
        "Y-0HVF",
        "regional"
    ],
    [
        "E-WMT7",
        "EU-WFW",
        "regional"
    ],
    [
        "F-5WYK",
        "OTJ9-E",
        "regional"
    ],
    [
        "J9A-BH",
        "DYS-CG",
        "regional"
    ],
    [
        "MTO2-2",
        "HD-JVQ",
        "regional"
    ],
    [
        "PA-ALN",
        "EU-WFW",
        "regional"
    ],
    [
        "PA-ALN",
        "L-EUY2",
        "regional"
    ],
    [
        "PFV-ZH",
        "9S-GPT",
        "regional"
    ],
    [
        "PVF-N9",
        "QZ1-OH",
        "regional"
    ],
    [
        "R-AG7W",
        "IF-KD1",
        "regional"
    ],
    [
        "XY-ZCI",
        "QE2-FS",
        "regional"
    ]
]

# ===== Planetary Interaction =====
PI_DATA = {
    "3LL-O0": [
        {
            "planet_id": 40326876,
            "name": "3LL-O0 I",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326878,
            "name": "3LL-O0 II",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326880,
            "name": "3LL-O0 III",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40326884,
            "name": "3LL-O0 IV",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40326887,
            "name": "3LL-O0 V",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40326891,
            "name": "3LL-O0 VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326911,
            "name": "3LL-O0 VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326932,
            "name": "3LL-O0 VIII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326968,
            "name": "3LL-O0 IX",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        },
        {
            "planet_id": 40326971,
            "name": "3LL-O0 X",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326974,
            "name": "3LL-O0 XI",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "49V-E4": [
        {
            "planet_id": 40326799,
            "name": "49V-E4 I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326801,
            "name": "49V-E4 II",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326802,
            "name": "49V-E4 III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326803,
            "name": "49V-E4 IV",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        },
        {
            "planet_id": 40326805,
            "name": "49V-E4 V",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326818,
            "name": "49V-E4 VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326840,
            "name": "49V-E4 VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        }
    ],
    "4F6-VZ": [
        {
            "planet_id": 40326423,
            "name": "4F6-VZ I",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326424,
            "name": "4F6-VZ II",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326425,
            "name": "4F6-VZ III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326427,
            "name": "4F6-VZ IV",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326428,
            "name": "4F6-VZ V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326430,
            "name": "4F6-VZ VI",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40326434,
            "name": "4F6-VZ VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326444,
            "name": "4F6-VZ VIII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326449,
            "name": "4F6-VZ IX",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326468,
            "name": "4F6-VZ X",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        },
        {
            "planet_id": 40326472,
            "name": "4F6-VZ XI",
            "type_id": 12,
            "type": "Planet (Ice)"
        }
    ],
    "5T-A3D": [
        {
            "planet_id": 40323700,
            "name": "5T-A3D I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323701,
            "name": "5T-A3D II",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40323703,
            "name": "5T-A3D III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323706,
            "name": "5T-A3D IV",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323709,
            "name": "5T-A3D V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323711,
            "name": "5T-A3D VI",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        },
        {
            "planet_id": 40323713,
            "name": "5T-A3D VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323740,
            "name": "5T-A3D VIII",
            "type_id": 2063,
            "type": "Planet (Plasma)"
        },
        {
            "planet_id": 40323742,
            "name": "5T-A3D IX",
            "type_id": 13,
            "type": "Planet (Gas)"
        }
    ],
    "5ZU-VG": [
        {
            "planet_id": 40323408,
            "name": "5ZU-VG I",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40323410,
            "name": "5ZU-VG II",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40323412,
            "name": "5ZU-VG III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323413,
            "name": "5ZU-VG IV",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323419,
            "name": "5ZU-VG V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323424,
            "name": "5ZU-VG VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323443,
            "name": "5ZU-VG VII",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323447,
            "name": "5ZU-VG VIII",
            "type_id": 13,
            "type": "Planet (Gas)"
        }
    ],
    "6-1T6Z": [
        {
            "planet_id": 40323481,
            "name": "6-1T6Z I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323482,
            "name": "6-1T6Z II",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323484,
            "name": "6-1T6Z III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323486,
            "name": "6-1T6Z IV",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40323489,
            "name": "6-1T6Z V",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323502,
            "name": "6-1T6Z VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323511,
            "name": "6-1T6Z VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323522,
            "name": "6-1T6Z VIII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323559,
            "name": "6-1T6Z IX",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "6-8QLA": [
        {
            "planet_id": 40323616,
            "name": "6-8QLA I",
            "type_id": 2063,
            "type": "Planet (Plasma)"
        },
        {
            "planet_id": 40323618,
            "name": "6-8QLA II",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40323619,
            "name": "6-8QLA III",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        },
        {
            "planet_id": 40323621,
            "name": "6-8QLA IV",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323632,
            "name": "6-8QLA V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323635,
            "name": "6-8QLA VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323642,
            "name": "6-8QLA VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323668,
            "name": "6-8QLA VIII",
            "type_id": 13,
            "type": "Planet (Gas)"
        }
    ],
    "8B-A4E": [
        {
            "planet_id": 40326756,
            "name": "8B-A4E I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326758,
            "name": "8B-A4E II",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326760,
            "name": "8B-A4E III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326761,
            "name": "8B-A4E IV",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326762,
            "name": "8B-A4E V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326763,
            "name": "8B-A4E VI",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326765,
            "name": "8B-A4E VII",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326767,
            "name": "8B-A4E VIII",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326770,
            "name": "8B-A4E IX",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326776,
            "name": "8B-A4E X",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326780,
            "name": "8B-A4E XI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326788,
            "name": "8B-A4E XII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326795,
            "name": "8B-A4E XIII",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "A1F-22": [
        {
            "planet_id": 40326980,
            "name": "A1F-22 I",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326982,
            "name": "A1F-22 II",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326983,
            "name": "A1F-22 III",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40326984,
            "name": "A1F-22 IV",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326988,
            "name": "A1F-22 V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326991,
            "name": "A1F-22 VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40327006,
            "name": "A1F-22 VII",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "B-7LYC": [
        {
            "planet_id": 40326478,
            "name": "B-7LYC I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326479,
            "name": "B-7LYC II",
            "type_id": 2063,
            "type": "Planet (Plasma)"
        },
        {
            "planet_id": 40326481,
            "name": "B-7LYC III",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326484,
            "name": "B-7LYC IV",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326485,
            "name": "B-7LYC V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326486,
            "name": "B-7LYC VI",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40326489,
            "name": "B-7LYC VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326496,
            "name": "B-7LYC VIII",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40326501,
            "name": "B-7LYC IX",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326510,
            "name": "B-7LYC X",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        }
    ],
    "EH2I-P": [
        {
            "planet_id": 40323337,
            "name": "EH2I-P I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323338,
            "name": "EH2I-P II",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323340,
            "name": "EH2I-P III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323342,
            "name": "EH2I-P IV",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40323345,
            "name": "EH2I-P V",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40323347,
            "name": "EH2I-P VI",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323350,
            "name": "EH2I-P VII",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323354,
            "name": "EH2I-P VIII",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "G-GRSZ": [
        {
            "planet_id": 40323587,
            "name": "G-GRSZ I",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40323588,
            "name": "G-GRSZ II",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323590,
            "name": "G-GRSZ III",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323593,
            "name": "G-GRSZ IV",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323594,
            "name": "G-GRSZ V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323598,
            "name": "G-GRSZ VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323604,
            "name": "G-GRSZ VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323611,
            "name": "G-GRSZ VIII",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323614,
            "name": "G-GRSZ IX",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "HB-KSF": [
        {
            "planet_id": 40323255,
            "name": "HB-KSF I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323256,
            "name": "HB-KSF II",
            "type_id": 2063,
            "type": "Planet (Plasma)"
        },
        {
            "planet_id": 40323257,
            "name": "HB-KSF III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323259,
            "name": "HB-KSF IV",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323262,
            "name": "HB-KSF V",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323281,
            "name": "HB-KSF VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323300,
            "name": "HB-KSF VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323324,
            "name": "HB-KSF VIII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323330,
            "name": "HB-KSF IX",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40323333,
            "name": "HB-KSF X",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "J9A-BH": [
        {
            "planet_id": 40326354,
            "name": "J9A-BH I",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326356,
            "name": "J9A-BH II",
            "type_id": 2063,
            "type": "Planet (Plasma)"
        },
        {
            "planet_id": 40326358,
            "name": "J9A-BH III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326360,
            "name": "J9A-BH IV",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326362,
            "name": "J9A-BH V",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326378,
            "name": "J9A-BH VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326383,
            "name": "J9A-BH VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326414,
            "name": "J9A-BH VIII",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        },
        {
            "planet_id": 40326417,
            "name": "J9A-BH IX",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "JM0A-4": [
        {
            "planet_id": 40326514,
            "name": "JM0A-4 I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326516,
            "name": "JM0A-4 II",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40326518,
            "name": "JM0A-4 III",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        },
        {
            "planet_id": 40326521,
            "name": "JM0A-4 IV",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40326523,
            "name": "JM0A-4 V",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326547,
            "name": "JM0A-4 VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326573,
            "name": "JM0A-4 VII",
            "type_id": 12,
            "type": "Planet (Ice)"
        },
        {
            "planet_id": 40326577,
            "name": "JM0A-4 VIII",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "L-POLO": [
        {
            "planet_id": 40326667,
            "name": "L-POLO I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326668,
            "name": "L-POLO II",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326670,
            "name": "L-POLO III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326671,
            "name": "L-POLO IV",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326690,
            "name": "L-POLO V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326692,
            "name": "L-POLO VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326722,
            "name": "L-POLO VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326744,
            "name": "L-POLO VIII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326750,
            "name": "L-POLO IX",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        }
    ],
    "LW-YEW": [
        {
            "planet_id": 40323190,
            "name": "LW-YEW I",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323192,
            "name": "LW-YEW II",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323197,
            "name": "LW-YEW III",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40323201,
            "name": "LW-YEW IV",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323205,
            "name": "LW-YEW V",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323226,
            "name": "LW-YEW VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323248,
            "name": "LW-YEW VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        }
    ],
    "OP7-BP": [
        {
            "planet_id": 40323359,
            "name": "OP7-BP I",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40323361,
            "name": "OP7-BP II",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323363,
            "name": "OP7-BP III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323365,
            "name": "OP7-BP IV",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40323368,
            "name": "OP7-BP V",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40323370,
            "name": "OP7-BP VI",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        },
        {
            "planet_id": 40323372,
            "name": "OP7-BP VII",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323375,
            "name": "OP7-BP VIII",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323378,
            "name": "OP7-BP IX",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323402,
            "name": "OP7-BP X",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        }
    ],
    "PT-2KR": [
        {
            "planet_id": 40326581,
            "name": "PT-2KR I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326583,
            "name": "PT-2KR II",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326585,
            "name": "PT-2KR III",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40326586,
            "name": "PT-2KR IV",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326606,
            "name": "PT-2KR V",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326632,
            "name": "PT-2KR VI",
            "type_id": 12,
            "type": "Planet (Ice)"
        }
    ],
    "R-AYGT": [
        {
            "planet_id": 40323564,
            "name": "R-AYGT I",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40323565,
            "name": "R-AYGT II",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323568,
            "name": "R-AYGT III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323572,
            "name": "R-AYGT IV",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323580,
            "name": "R-AYGT V",
            "type_id": 13,
            "type": "Planet (Gas)"
        }
    ]
}
