"""
Deployment: lawn-perrigen
Auto-generated by tools/bootstrap_deployment.py at 2026-05-05T03:16:04Z
Region: Perrigen Falls (10000066)
Primary constellations: 9BGY-6, WXB-RY

Re-run the bootstrap to refresh region geography, gate connections, and PI
data. The MAP_LAYOUT and MAP_LAYOUT_SUBWAY positions are starter values from
an automatic layout — hand-tune them for readability, then keep them in
source control. SYSTEM_UPGRADES is intentionally empty: populate it as
upgrades are installed in-game.
"""

DEPLOYMENT_ID = 'lawn-perrigen'

ALLIANCE = {
    "id": 150097440,
    "name": "Get Off My Lawn",
    "ticker": "LAWN",
    "short_name": "LAWN",
    "display_name": "GET OFF MY LAWN"
}

REGION = {
    "id": 10000066,
    "name": "Perrigen Falls"
}

PRIMARY_CONSTELLATION_IDS = [
    20000748,
    20000755
]
PRIMARY_CONSTELLATION_NAMES = [
    "9BGY-6",
    "WXB-RY"
]

# ===== Friendlies and threat tracking (manually maintained) =====
# Copy these from your previous deployment when migrating, or fill in fresh.
# Updated June 2026: LAWN joined the RMC coalition — most +5s below are RMC
# members. IDs resolved via ESI POST /universe/ids/.
# The old mini coalition is gone: BorderZone folded under the pressure of
# B0SS's war and evac'd (may not stay +10 but remains an ally on standings),
# and The Skeleton Crew never joined the Perrigen Falls move — they're a
# standings-only +5 now, not a coalition partner.
FRIENDLY_ALLIANCE_IDS = [
    # --- +10 blue ---
    99012845,    # BorderZone (folded/evac'd — see note above)
    99013982,    # Gnomes Rising HoA (LAWN highsec alliance)
    99014614,    # InnerZone (BorderZone HS alts — same caveat as BorderZone)
    # --- +5 light blue (mostly RMC) ---
    99009758,    # Absolute Will
    99013780,    # Advent Coalition
    99010549,    # Against ALL Authorities.
    99006132,    # Bad Wolf Industries Inc
    99011248,    # Big Green Fly
    99013532,    # Burning Contingent Holdings
    99012575,    # Care-Free Coalition
    99012586,    # Care-Less Collective
    99013823,    # Cat Scratch Fevers
    99011990,    # D3ad End
    99009805,    # Dead Game Society.
    99012018,    # EDENCOM DEFENSIVE INITIATIVE
    99008697,    # GF Company
    99013739,    # Heirs To The Pleasurehub
    99012122,    # HOLD MY PROBS
    99011292,    # Ice.Road.Truckers.
    99014427,    # Itty Bitty Asteroid Academy
    99013502,    # Itty Bitty Asteroid Committee
    1411711376,  # Legion of xXDEATHXx
    99014948,    # Legion of xXDEATHXx Holding
    99011416,    # LinkNet
    99014526,    # Lunar Fluorescence
    99014050,    # Lunar Luminescence
    99013713,    # MAXIMUS Alliance
    431502563,   # Ministry of Inappropriate Footwork
    99010389,    # Outsmarted
    99014362,    # Paws n Claws Collective
    99014402,    # Plenitude Alliance
    1220922756,  # Red Alliance
    99011268,    # Reeloaded.
    99014396,    # RS Rangers
    99003500,    # Shadow of xXDEATHXx
    99012279,    # Sportmodel
    99012328,    # STAKAN UNIVERSE
    99014852,    # Storm of the Freeborn
    99010484,    # The Burning Contingent Alliance
    99013028,    # The Monarchy
    99007969,    # THE RUSSIA
    99008788,    # The Skeleton Crew
    99012763,    # The Syndicate of Silence
    99014321,    # Tilean Dominium
    99011802,    # Warriors of the Blood God
    99014221,    # Weapons of Mass Logistics
    99010468,    # Weapons Of Mass Production.
    99006751,    # What Could Possibly Go Wr0ng
    99012572,    # Wildlife
    99006557,    # Wildly Inappropriate.
    99014161,    # Zombie Ninja Space Bears
]

FRIENDLY_ALLIANCES = [
    # Removed: Get Off My Lawn — the primary alliance is filtered directly in
    # routes via LAWN_ALLIANCE_ID / PRIMARY_ALLIANCE_ID; keeping it out keeps
    # this list parallel with FRIENDLY_ALLIANCE_IDS.
    # +10 blue
    "BorderZone",
    "Gnomes Rising HoA",
    "InnerZone",
    # +5 light blue (mostly RMC)
    "Absolute Will",
    "Advent Coalition",
    "Against ALL Authorities.",
    "Bad Wolf Industries Inc",
    "Big Green Fly",
    "Burning Contingent Holdings",
    "Care-Free Coalition",
    "Care-Less Collective",
    "Cat Scratch Fevers",
    "D3ad End",
    "Dead Game Society.",
    "EDENCOM DEFENSIVE INITIATIVE",
    "GF Company",
    "Heirs To The Pleasurehub",
    "HOLD MY PROBS",
    "Ice.Road.Truckers.",
    "Itty Bitty Asteroid Academy",
    "Itty Bitty Asteroid Committee",
    "Legion of xXDEATHXx",
    "Legion of xXDEATHXx Holding",
    "LinkNet",
    "Lunar Fluorescence",
    "Lunar Luminescence",
    "MAXIMUS Alliance",
    "Ministry of Inappropriate Footwork",
    "Outsmarted",
    "Paws n Claws Collective",
    "Plenitude Alliance",
    "Red Alliance",
    "Reeloaded.",
    "RS Rangers",
    "Shadow of xXDEATHXx",
    "Sportmodel",
    "STAKAN UNIVERSE",
    "Storm of the Freeborn",
    "The Burning Contingent Alliance",
    "The Monarchy",
    "THE RUSSIA",
    "The Skeleton Crew",
    "The Syndicate of Silence",
    "Tilean Dominium",
    "Warriors of the Blood God",
    "Weapons of Mass Logistics",
    "Weapons Of Mass Production.",
    "What Could Possibly Go Wr0ng",
    "Wildlife",
    "Wildly Inappropriate.",
    "Zombie Ninja Space Bears",
]

# Standalone corporations (no alliance) on the standings list at +5.
# Kept separate from FRIENDLY_CORPORATIONS, which means LAWN member corps:
# pilots in these corps classify as "friendly", not "lawn".
FRIENDLY_STANDING_CORPORATIONS = [
    {"name": "Coerce Inc", "id": 875653347},
    {"name": "Crazy Shenanigans", "id": 98699627},
    {"name": "GF Trade Corporation", "id": 98691848},
    {"name": "MOONFIRE SERVICE PROVIDER", "id": 98681117},
    {"name": "Rus Space Rangers", "id": 98695322},
    {"name": "Silent Nomads", "id": 98644242},
    {"name": "TnB Haul'n", "id": 98830270},
    {"name": "Totally Legit Business Venture", "id": 98742559},
]

FRIENDLY_CORPORATIONS = [
    "Astrum Mechanica",
    "DarkMatterEnterprises",
    "Derp Company",
    "Dormir no da ISK",
    "Gnome Tactical Foundations and Orientation",
    "Gnomeland Services",
    "Gnomes von Zurich",
    "Gnomestead Structures",
    "LAWN HC",
    "Moo-Tang Clan",
    "Obsidian Engineering",
    "Undersized Armada"
]

NEIGHBOR_ENTITIES = [
    # Active war target
    {
        "name": "Brotherhood of Spacers",
        "id": 99007887,
        "type": "alliance"
    },
    # Still active threats in Perrigen / surrounding space
    {
        "name": "PUT THE FRIES IN THE BAG",
        "id": 99014518,
        "type": "alliance"
    },
    {
        "name": "Deepwater Hooligans",
        "id": 99009927,
        "type": "alliance"
    },
    # Removed: The Rejected. [TRD] — not a threat in Perrigen Falls
]

# ===== Region geography (auto-generated) =====
# Systems just outside the primary region that share a gate with one of our
# systems. Used by SystemState.resolve_all_systems for the early-warning panel.
NEIGHBOR_SYSTEM_NAMES = [
    "9S-GPT",
    "DYS-CG",
    "EU-WFW",
    "HD-JVQ",
    "IF-KD1",
    "L-EUY2",
    "MTGF-2",
    "O8W-5O",
    "OTJ9-E",
    "QCGG-Q",
    "QE2-FS",
    "QZ1-OH",
    "Y-0HVF",
    "Z-DRIY"
]

PRIMARY_SYSTEMS = [
    "3LL-O0",
    "49V-E4",
    "4F6-VZ",
    "5T-A3D",
    "5ZU-VG",
    "6-1T6Z",
    "6-8QLA",
    "8B-A4E",
    "A1F-22",
    "B-7LYC",
    "EH2I-P",
    "G-GRSZ",
    "HB-KSF",
    "J9A-BH",
    "JM0A-4",
    "L-POLO",
    "LW-YEW",
    "OP7-BP",
    "PT-2KR",
    "R-AYGT"
]

BORDER_SYSTEMS = [
    "5T-A3D",
    "5ZU-VG",
    "6-1T6Z",
    "J9A-BH",
    "LW-YEW"
]

# ===== Sov upgrades (manual — populate as upgrades are installed) =====
# ICE entries mark systems with a natural ice belt (not an installed iHub upgrade).
SYSTEM_UPGRADES = {
    # 9BGY-6 constellation
    "6-1T6Z": [{"type": "mTD", "level": 1}],
    "HB-KSF": [{"type": "mTD", "level": 1}],
    "LW-YEW": [{"type": "mTD", "level": 1}],
    "5ZU-VG": [{"type": "MTD", "level": 1}],
    "5T-A3D": [{"type": "MTD", "level": 1}],
    "6-8QLA": [{"type": "ICE", "level": 1}],
    "EH2I-P": [{"type": "ICE", "level": 1}],
    "G-GRSZ": [{"type": "ICE", "level": 1}],
    "OP7-BP": [{"type": "MTD", "level": 2}, {"type": "ICE", "level": 1}],
    "R-AYGT": [{"type": "MTD", "level": 3}],
    # WXB-RY constellation
    "J9A-BH": [{"type": "MTD",    "level": 2}],
    "49V-E4": [{"type": "MTD",    "level": 2}],
    "B-7LYC": [{"type": "MTD",    "level": 3}, {"type": "ICE", "level": 1}],
    "PT-2KR": [{"type": "mTD",    "level": 3}],
    "4F6-VZ": [{"type": "MTD",    "level": 3}],
    "JM0A-4": [{"type": "MTD",    "level": 3}],
    "A1F-22": [{"type": "MTD",    "level": 3}],
    "L-POLO": [{"type": "PA_Nocx","level": 2}],
    "8B-A4E": [{"type": "PA_Iso", "level": 3}],
    "3LL-O0": [{"type": "PA_Mex", "level": 3}, {"type": "ICE", "level": 1}],
}

# ===== Map layout (auto-generated, hand-tune for readability) =====
MAP_LAYOUT = {
    "0-U2M4": {
        "x": -14,
        "y": 78,
        "constellation": "TPB-KG"
    },
    "01B-88": {
        "x": 74,
        "y": 106,
        "constellation": "TPB-KG"
    },
    "0FG-KS": {
        "x": 830,
        "y": 525,
        "constellation": "B-MQ0Y"
    },
    "0XN-SK": {
        "x": 629,
        "y": 577,
        "constellation": "TY0-Q2"
    },
    "1A8-6G": {
        "x": 230,
        "y": 521,
        "constellation": "X7-FTR"
    },
    "2-YO2K": {
        "x": 48,
        "y": 657,
        "constellation": "BXT7-V"
    },
    "2AUL-X": {
        "x": 1081,
        "y": 351,
        "constellation": "S0X-O4"
    },
    "2V-ZHM": {
        "x": 48,
        "y": 525,
        "constellation": "O5PO-O"
    },
    "3LL-O0": {
        "x": 1136,
        "y": 105,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "4-1ECP": {
        "x": 249,
        "y": 98,
        "constellation": "L7-RDZ"
    },
    "4-M1TY": {
        "x": 325,
        "y": 638,
        "constellation": "X7-FTR"
    },
    "49V-E4": {
        "x": 800,
        "y": 233,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "4F6-VZ": {
        "x": 1118,
        "y": 159,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "4F9Y-3": {
        "x": 629,
        "y": 525,
        "constellation": "TY0-Q2"
    },
    "5-U12M": {
        "x": 162,
        "y": 126,
        "constellation": "L7-RDZ"
    },
    "5T-A3D": {
        "x": 490,
        "y": 193,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "5V-Q1R": {
        "x": 540,
        "y": 525,
        "constellation": "TY0-Q2"
    },
    "5ZU-VG": {
        "x": 596,
        "y": 139,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "6-1T6Z": {
        "x": 356,
        "y": 105,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "6-8QLA": {
        "x": 356,
        "y": 279,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "6Q4-X6": {
        "x": 615,
        "y": 36,
        "constellation": "4LEZ-6"
    },
    "7AH-SF": {
        "x": 260,
        "y": 126,
        "constellation": "L7-RDZ"
    },
    "7JRA-G": {
        "x": 399,
        "y": 398,
        "constellation": "LWMW-6"
    },
    "7M4-4C": {
        "x": -196,
        "y": 295,
        "constellation": "VT-LHB"
    },
    "7MMJ-3": {
        "x": 249,
        "y": 186,
        "constellation": "L7-RDZ"
    },
    "8B-A4E": {
        "x": 1270,
        "y": 227,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "9-EXU9": {
        "x": 190,
        "y": 154,
        "constellation": "L7-RDZ"
    },
    "9-ZA4Z": {
        "x": 696,
        "y": 389,
        "constellation": "Q0-4FU"
    },
    "972C-1": {
        "x": -108,
        "y": 384,
        "constellation": "VT-LHB"
    },
    "9IZ-HU": {
        "x": 911,
        "y": 328,
        "constellation": "S0X-O4"
    },
    "9S-GPT": {
        "x": 210,
        "y": 427,
        "constellation": "neighbor",
        "note": "Outer Passage"
    },
    "9WVY-F": {
        "x": -196,
        "y": 384,
        "constellation": "VT-LHB"
    },
    "A1F-22": {
        "x": 1270,
        "y": 91,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "A9-F18": {
        "x": 129,
        "y": 445,
        "constellation": "NT1-5Q"
    },
    "AK-L0Z": {
        "x": 134,
        "y": 549,
        "constellation": "O5PO-O"
    },
    "AY9X-Q": {
        "x": -115,
        "y": 483,
        "constellation": "O5PO-O"
    },
    "B-7LYC": {
        "x": 790,
        "y": 173,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "B-B0ME": {
        "x": 94,
        "y": 309,
        "constellation": "NT1-5Q"
    },
    "B9N2-2": {
        "x": 703,
        "y": 36,
        "constellation": "4LEZ-6"
    },
    "BEG-RL": {
        "x": -21,
        "y": 337,
        "constellation": "VT-LHB"
    },
    "C3I-D5": {
        "x": 189,
        "y": 41,
        "constellation": "TPB-KG"
    },
    "C6CG-W": {
        "x": 440,
        "y": 539,
        "constellation": "X7-FTR"
    },
    "D-QJR9": {
        "x": 715,
        "y": 69,
        "constellation": "4LEZ-6"
    },
    "DE-IHK": {
        "x": 432,
        "y": 250,
        "constellation": "NT1-5Q"
    },
    "DYS-CG": {
        "x": 925,
        "y": 210,
        "constellation": "neighbor",
        "note": "Oasa"
    },
    "E-WMT7": {
        "x": 986,
        "y": 477,
        "constellation": "B-MQ0Y"
    },
    "EF-QZK": {
        "x": 797,
        "y": 487,
        "constellation": "B-MQ0Y"
    },
    "EH2I-P": {
        "x": 490,
        "y": 247,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "EU-WFW": {
        "x": 1033,
        "y": 441,
        "constellation": "neighbor",
        "note": "The Spire"
    },
    "F-5WYK": {
        "x": 906,
        "y": 483,
        "constellation": "B-MQ0Y"
    },
    "F-A3TR": {
        "x": 993,
        "y": 290,
        "constellation": "S0X-O4"
    },
    "F-HQWV": {
        "x": 993,
        "y": 244,
        "constellation": "S0X-O4"
    },
    "F18-AY": {
        "x": 129,
        "y": 78,
        "constellation": "TPB-KG"
    },
    "FLK-LJ": {
        "x": 939,
        "y": 525,
        "constellation": "B-MQ0Y"
    },
    "G-GRSZ": {
        "x": 634,
        "y": 333,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "H-29TM": {
        "x": 662,
        "y": 102,
        "constellation": "4LEZ-6"
    },
    "H-FOYG": {
        "x": 134,
        "y": 487,
        "constellation": "X7-FTR"
    },
    "H-HGGJ": {
        "x": 94,
        "y": 384,
        "constellation": "NT1-5Q"
    },
    "HB-KSF": {
        "x": 288,
        "y": 159,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "HD-JVQ": {
        "x": -141,
        "y": 46,
        "constellation": "neighbor",
        "note": "Venal"
    },
    "IF-KD1": {
        "x": -196,
        "y": 567,
        "constellation": "neighbor",
        "note": "Malpais"
    },
    "IU-E9T": {
        "x": 588,
        "y": 375,
        "constellation": "Q0-4FU"
    },
    "J9A-BH": {
        "x": 982,
        "y": 153,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "JM0A-4": {
        "x": 1270,
        "y": 145,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "JPEZ-R": {
        "x": -148,
        "y": 220,
        "constellation": "VT-LHB"
    },
    "JZ-UQC": {
        "x": -196,
        "y": 337,
        "constellation": "VT-LHB"
    },
    "K-3PQW": {
        "x": 337,
        "y": 563,
        "constellation": "X7-FTR"
    },
    "KOI8-Z": {
        "x": 756,
        "y": 102,
        "constellation": "4LEZ-6"
    },
    "L-EUY2": {
        "x": 939,
        "y": 393,
        "constellation": "neighbor",
        "note": "The Spire"
    },
    "L-POLO": {
        "x": 1156,
        "y": 205,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "L5Y4-M": {
        "x": 304,
        "y": 403,
        "constellation": "LWMW-6"
    },
    "LW-YEW": {
        "x": 356,
        "y": 227,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "M-SG47": {
        "x": -95,
        "y": 722,
        "constellation": "BXT7-V"
    },
    "M4-KX5": {
        "x": 533,
        "y": 577,
        "constellation": "TY0-Q2"
    },
    "M5NO-B": {
        "x": -148,
        "y": 258,
        "constellation": "VT-LHB"
    },
    "MJ-5F9": {
        "x": -27,
        "y": 262,
        "constellation": "VT-LHB"
    },
    "MS-RXH": {
        "x": 567,
        "y": 477,
        "constellation": "TY0-Q2"
    },
    "MTGF-2": {
        "x": 520,
        "y": 108,
        "constellation": "neighbor",
        "note": "Oasa"
    },
    "MTO2-2": {
        "x": -41,
        "y": 41,
        "constellation": "TPB-KG"
    },
    "NGM-OK": {
        "x": 675,
        "y": 347,
        "constellation": "Q0-4FU"
    },
    "O-QKSM": {
        "x": 574,
        "y": 337,
        "constellation": "Q0-4FU"
    },
    "O8W-5O": {
        "x": -196,
        "y": 483,
        "constellation": "neighbor",
        "note": "Malpais"
    },
    "OBV-YC": {
        "x": 1095,
        "y": 309,
        "constellation": "S0X-O4"
    },
    "OJT-J3": {
        "x": 256,
        "y": 238,
        "constellation": "NT1-5Q"
    },
    "OP7-BP": {
        "x": 616,
        "y": 213,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "OTJ9-E": {
        "x": 865,
        "y": 441,
        "constellation": "neighbor",
        "note": "The Spire"
    },
    "PA-ALN": {
        "x": 1061,
        "y": 398,
        "constellation": "S0X-O4"
    },
    "PE-SAM": {
        "x": 330,
        "y": 529,
        "constellation": "X7-FTR"
    },
    "PFV-ZH": {
        "x": 297,
        "y": 449,
        "constellation": "LWMW-6"
    },
    "PT-2KR": {
        "x": 856,
        "y": 119,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "PVF-N9": {
        "x": 108,
        "y": 172,
        "constellation": "L7-RDZ"
    },
    "QCGG-Q": {
        "x": 189,
        "y": 304,
        "constellation": "neighbor",
        "note": "Malpais"
    },
    "QE2-FS": {
        "x": 399,
        "y": 332,
        "constellation": "neighbor",
        "note": "Oasa"
    },
    "QHY-RU": {
        "x": 101,
        "y": 704,
        "constellation": "BXT7-V"
    },
    "QKQ3-L": {
        "x": 507,
        "y": 314,
        "constellation": "Q0-4FU"
    },
    "QZ1-OH": {
        "x": -7,
        "y": 154,
        "constellation": "neighbor",
        "note": "Malpais"
    },
    "R-AG7W": {
        "x": -115,
        "y": 567,
        "constellation": "O5PO-O"
    },
    "R-AYGT": {
        "x": 558,
        "y": 293,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "RY-2FX": {
        "x": 230,
        "y": 563,
        "constellation": "X7-FTR"
    },
    "RZ3O-K": {
        "x": 715,
        "y": 543,
        "constellation": "B-MQ0Y"
    },
    "RZ8A-P": {
        "x": 60,
        "y": 50,
        "constellation": "TPB-KG"
    },
    "SR-10Z": {
        "x": 7,
        "y": 704,
        "constellation": "BXT7-V"
    },
    "SY-OLX": {
        "x": 480,
        "y": 435,
        "constellation": "LWMW-6"
    },
    "TAL1-3": {
        "x": 216,
        "y": 722,
        "constellation": "BXT7-V"
    },
    "TDP-T3": {
        "x": 155,
        "y": 248,
        "constellation": "NT1-5Q"
    },
    "U-3FKL": {
        "x": 595,
        "y": 431,
        "constellation": "TY0-Q2"
    },
    "U-W436": {
        "x": -108,
        "y": 337,
        "constellation": "VT-LHB"
    },
    "U4-V3J": {
        "x": 595,
        "y": 69,
        "constellation": "4LEZ-6"
    },
    "UYOC-1": {
        "x": 358,
        "y": 50,
        "constellation": "L7-RDZ"
    },
    "V-3K7C": {
        "x": 55,
        "y": 483,
        "constellation": "O5PO-O"
    },
    "VWES-Y": {
        "x": 433,
        "y": 290,
        "constellation": "Q0-4FU"
    },
    "W-CSFY": {
        "x": 392,
        "y": 449,
        "constellation": "LWMW-6"
    },
    "W-KXEX": {
        "x": -189,
        "y": 722,
        "constellation": "BXT7-V"
    },
    "XU7-CH": {
        "x": -48,
        "y": 521,
        "constellation": "O5PO-O"
    },
    "XY-ZCI": {
        "x": 466,
        "y": 375,
        "constellation": "LWMW-6"
    },
    "Y-0HVF": {
        "x": 318,
        "y": 41,
        "constellation": "neighbor",
        "note": "Oasa"
    },
    "Z-DRIY": {
        "x": 0,
        "y": 375,
        "constellation": "neighbor",
        "note": "Etherium Reach"
    },
    "Z-ENUD": {
        "x": -108,
        "y": 295,
        "constellation": "VT-LHB"
    }
}

MAP_LAYOUT_SUBWAY = {
    "0-U2M4": {
        "x": 52,
        "y": 221,
        "constellation": "TPB-KG"
    },
    "01B-88": {
        "x": 130,
        "y": 254,
        "constellation": "TPB-KG"
    },
    "0FG-KS": {
        "x": 702,
        "y": 1001,
        "constellation": "B-MQ0Y"
    },
    "0XN-SK": {
        "x": 520,
        "y": 1066,
        "constellation": "TY0-Q2"
    },
    "1A8-6G": {
        "x": 234,
        "y": 871,
        "constellation": "X7-FTR"
    },
    "2-YO2K": {
        "x": 52,
        "y": 1034,
        "constellation": "BXT7-V"
    },
    "2AUL-X": {
        "x": 832,
        "y": 871,
        "constellation": "S0X-O4"
    },
    "2V-ZHM": {
        "x": 52,
        "y": 871,
        "constellation": "O5PO-O"
    },
    "3LL-O0": {
        "x": 1024,
        "y": 481,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "4-1ECP": {
        "x": 312,
        "y": 221,
        "constellation": "L7-RDZ"
    },
    "4-M1TY": {
        "x": 312,
        "y": 1001,
        "constellation": "X7-FTR"
    },
    "49V-E4": {
        "x": 624,
        "y": 581,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "4F6-VZ": {
        "x": 784,
        "y": 481,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "4F9Y-3": {
        "x": 520,
        "y": 1001,
        "constellation": "TY0-Q2"
    },
    "5-U12M": {
        "x": 208,
        "y": 254,
        "constellation": "L7-RDZ"
    },
    "5T-A3D": {
        "x": 464,
        "y": 381,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "5V-Q1R": {
        "x": 416,
        "y": 1001,
        "constellation": "TY0-Q2"
    },
    "5ZU-VG": {
        "x": 544,
        "y": 381,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "6-1T6Z": {
        "x": 544,
        "y": 281,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "6-8QLA": {
        "x": 304,
        "y": 481,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "6Q4-X6": {
        "x": 572,
        "y": 188,
        "constellation": "4LEZ-6"
    },
    "7AH-SF": {
        "x": 468,
        "y": 188,
        "constellation": "L7-RDZ"
    },
    "7JRA-G": {
        "x": 442,
        "y": 708,
        "constellation": "LWMW-6"
    },
    "7M4-4C": {
        "x": -130,
        "y": 481,
        "constellation": "VT-LHB"
    },
    "7MMJ-3": {
        "x": 312,
        "y": 351,
        "constellation": "L7-RDZ"
    },
    "8B-A4E": {
        "x": 784,
        "y": 681,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "9-EXU9": {
        "x": 312,
        "y": 286,
        "constellation": "L7-RDZ"
    },
    "9-ZA4Z": {
        "x": 572,
        "y": 838,
        "constellation": "Q0-4FU"
    },
    "972C-1": {
        "x": -52,
        "y": 578,
        "constellation": "VT-LHB"
    },
    "9IZ-HU": {
        "x": 806,
        "y": 741,
        "constellation": "S0X-O4"
    },
    "9S-GPT": {
        "x": 208,
        "y": 741,
        "constellation": "neighbor",
        "note": "Outer Passage"
    },
    "9WVY-F": {
        "x": -130,
        "y": 578,
        "constellation": "VT-LHB"
    },
    "A1F-22": {
        "x": 944,
        "y": 481,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "A9-F18": {
        "x": 130,
        "y": 774,
        "constellation": "NT1-5Q"
    },
    "AK-L0Z": {
        "x": 130,
        "y": 904,
        "constellation": "O5PO-O"
    },
    "AY9X-Q": {
        "x": -52,
        "y": 708,
        "constellation": "O5PO-O"
    },
    "B-7LYC": {
        "x": 624,
        "y": 481,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "B-B0ME": {
        "x": 156,
        "y": 514,
        "constellation": "NT1-5Q"
    },
    "B9N2-2": {
        "x": 650,
        "y": 188,
        "constellation": "4LEZ-6"
    },
    "BEG-RL": {
        "x": 52,
        "y": 546,
        "constellation": "VT-LHB"
    },
    "C3I-D5": {
        "x": 234,
        "y": 156,
        "constellation": "TPB-KG"
    },
    "C6CG-W": {
        "x": 442,
        "y": 871,
        "constellation": "X7-FTR"
    },
    "D-QJR9": {
        "x": 728,
        "y": 221,
        "constellation": "4LEZ-6"
    },
    "DE-IHK": {
        "x": 286,
        "y": 384,
        "constellation": "NT1-5Q"
    },
    "DYS-CG": {
        "x": 780,
        "y": 384,
        "constellation": "neighbor",
        "note": "Oasa"
    },
    "E-WMT7": {
        "x": 728,
        "y": 1034,
        "constellation": "B-MQ0Y"
    },
    "EF-QZK": {
        "x": 676,
        "y": 936,
        "constellation": "B-MQ0Y"
    },
    "EH2I-P": {
        "x": 384,
        "y": 481,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "EU-WFW": {
        "x": 780,
        "y": 1001,
        "constellation": "neighbor",
        "note": "The Spire"
    },
    "F-5WYK": {
        "x": 806,
        "y": 936,
        "constellation": "B-MQ0Y"
    },
    "F-A3TR": {
        "x": 850,
        "y": 741,
        "constellation": "S0X-O4"
    },
    "F-HQWV": {
        "x": 858,
        "y": 644,
        "constellation": "S0X-O4"
    },
    "F18-AY": {
        "x": 182,
        "y": 221,
        "constellation": "TPB-KG"
    },
    "FLK-LJ": {
        "x": 832,
        "y": 1001,
        "constellation": "B-MQ0Y"
    },
    "G-GRSZ": {
        "x": 384,
        "y": 681,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "H-29TM": {
        "x": 624,
        "y": 286,
        "constellation": "4LEZ-6"
    },
    "H-FOYG": {
        "x": 130,
        "y": 806,
        "constellation": "X7-FTR"
    },
    "H-HGGJ": {
        "x": 156,
        "y": 578,
        "constellation": "NT1-5Q"
    },
    "HB-KSF": {
        "x": 384,
        "y": 281,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "HD-JVQ": {
        "x": -78,
        "y": 156,
        "constellation": "neighbor",
        "note": "Venal"
    },
    "IF-KD1": {
        "x": -130,
        "y": 838,
        "constellation": "neighbor",
        "note": "Malpais"
    },
    "IU-E9T": {
        "x": 520,
        "y": 741,
        "constellation": "Q0-4FU"
    },
    "J9A-BH": {
        "x": 704,
        "y": 481,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "JM0A-4": {
        "x": 864,
        "y": 481,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "JPEZ-R": {
        "x": -78,
        "y": 384,
        "constellation": "VT-LHB"
    },
    "JZ-UQC": {
        "x": -130,
        "y": 546,
        "constellation": "VT-LHB"
    },
    "K-3PQW": {
        "x": 338,
        "y": 904,
        "constellation": "X7-FTR"
    },
    "KOI8-Z": {
        "x": 754,
        "y": 351,
        "constellation": "4LEZ-6"
    },
    "L-EUY2": {
        "x": 875,
        "y": 838,
        "constellation": "neighbor",
        "note": "The Spire"
    },
    "L-POLO": {
        "x": 784,
        "y": 581,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "L5Y4-M": {
        "x": 312,
        "y": 708,
        "constellation": "LWMW-6"
    },
    "LW-YEW": {
        "x": 384,
        "y": 381,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "M-SG47": {
        "x": -78,
        "y": 1131,
        "constellation": "BXT7-V"
    },
    "M4-KX5": {
        "x": 416,
        "y": 1066,
        "constellation": "TY0-Q2"
    },
    "M5NO-B": {
        "x": -78,
        "y": 448,
        "constellation": "VT-LHB"
    },
    "MJ-5F9": {
        "x": 26,
        "y": 448,
        "constellation": "VT-LHB"
    },
    "MS-RXH": {
        "x": 442,
        "y": 936,
        "constellation": "TY0-Q2"
    },
    "MTGF-2": {
        "x": 468,
        "y": 254,
        "constellation": "neighbor",
        "note": "Oasa"
    },
    "MTO2-2": {
        "x": 26,
        "y": 156,
        "constellation": "TPB-KG"
    },
    "NGM-OK": {
        "x": 546,
        "y": 774,
        "constellation": "Q0-4FU"
    },
    "O-QKSM": {
        "x": 520,
        "y": 708,
        "constellation": "Q0-4FU"
    },
    "O8W-5O": {
        "x": -130,
        "y": 708,
        "constellation": "neighbor",
        "note": "Malpais"
    },
    "OBV-YC": {
        "x": 832,
        "y": 838,
        "constellation": "S0X-O4"
    },
    "OJT-J3": {
        "x": 260,
        "y": 481,
        "constellation": "NT1-5Q"
    },
    "OP7-BP": {
        "x": 544,
        "y": 481,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "OTJ9-E": {
        "x": 728,
        "y": 904,
        "constellation": "neighbor",
        "note": "The Spire"
    },
    "PA-ALN": {
        "x": 850,
        "y": 936,
        "constellation": "S0X-O4"
    },
    "PE-SAM": {
        "x": 338,
        "y": 871,
        "constellation": "X7-FTR"
    },
    "PFV-ZH": {
        "x": 286,
        "y": 774,
        "constellation": "LWMW-6"
    },
    "PT-2KR": {
        "x": 704,
        "y": 381,
        "constellation": "WXB-RY",
        "lawn": True
    },
    "PVF-N9": {
        "x": 156,
        "y": 318,
        "constellation": "L7-RDZ"
    },
    "QCGG-Q": {
        "x": 234,
        "y": 481,
        "constellation": "neighbor",
        "note": "Malpais"
    },
    "QE2-FS": {
        "x": 442,
        "y": 644,
        "constellation": "neighbor",
        "note": "Oasa"
    },
    "QHY-RU": {
        "x": 104,
        "y": 1098,
        "constellation": "BXT7-V"
    },
    "QKQ3-L": {
        "x": 494,
        "y": 611,
        "constellation": "Q0-4FU"
    },
    "QZ1-OH": {
        "x": 52,
        "y": 318,
        "constellation": "neighbor",
        "note": "Malpais"
    },
    "R-AG7W": {
        "x": -104,
        "y": 936,
        "constellation": "O5PO-O"
    },
    "R-AYGT": {
        "x": 384,
        "y": 581,
        "constellation": "9BGY-6",
        "lawn": True
    },
    "RY-2FX": {
        "x": 234,
        "y": 904,
        "constellation": "X7-FTR"
    },
    "RZ3O-K": {
        "x": 598,
        "y": 1034,
        "constellation": "B-MQ0Y"
    },
    "RZ8A-P": {
        "x": 130,
        "y": 188,
        "constellation": "TPB-KG"
    },
    "SR-10Z": {
        "x": 26,
        "y": 1098,
        "constellation": "BXT7-V"
    },
    "SY-OLX": {
        "x": 468,
        "y": 741,
        "constellation": "LWMW-6"
    },
    "TAL1-3": {
        "x": 208,
        "y": 1131,
        "constellation": "BXT7-V"
    },
    "TDP-T3": {
        "x": 208,
        "y": 416,
        "constellation": "NT1-5Q"
    },
    "U-3FKL": {
        "x": 468,
        "y": 871,
        "constellation": "TY0-Q2"
    },
    "U-W436": {
        "x": -52,
        "y": 546,
        "constellation": "VT-LHB"
    },
    "U4-V3J": {
        "x": 520,
        "y": 188,
        "constellation": "4LEZ-6"
    },
    "UYOC-1": {
        "x": 416,
        "y": 221,
        "constellation": "L7-RDZ"
    },
    "V-3K7C": {
        "x": 52,
        "y": 806,
        "constellation": "O5PO-O"
    },
    "VWES-Y": {
        "x": 468,
        "y": 578,
        "constellation": "Q0-4FU"
    },
    "W-CSFY": {
        "x": 390,
        "y": 774,
        "constellation": "LWMW-6"
    },
    "W-KXEX": {
        "x": -182,
        "y": 1131,
        "constellation": "BXT7-V"
    },
    "XU7-CH": {
        "x": -26,
        "y": 871,
        "constellation": "O5PO-O"
    },
    "XY-ZCI": {
        "x": 468,
        "y": 676,
        "constellation": "LWMW-6"
    },
    "Y-0HVF": {
        "x": 364,
        "y": 156,
        "constellation": "neighbor",
        "note": "Oasa"
    },
    "Z-DRIY": {
        "x": 52,
        "y": 578,
        "constellation": "neighbor",
        "note": "Etherium Reach"
    },
    "Z-ENUD": {
        "x": -52,
        "y": 481,
        "constellation": "VT-LHB"
    }
}

MAP_CONNECTIONS = [
    [
        "1A8-6G",
        "2V-ZHM",
        "cross"
    ],
    [
        "5-U12M",
        "01B-88",
        "cross"
    ],
    [
        "5ZU-VG",
        "H-29TM",
        "cross"
    ],
    [
        "6-1T6Z",
        "7AH-SF",
        "cross"
    ],
    [
        "9IZ-HU",
        "9-ZA4Z",
        "cross"
    ],
    [
        "AK-L0Z",
        "2-YO2K",
        "cross"
    ],
    [
        "AK-L0Z",
        "H-FOYG",
        "cross"
    ],
    [
        "C6CG-W",
        "5V-Q1R",
        "cross"
    ],
    [
        "DE-IHK",
        "LW-YEW",
        "cross"
    ],
    [
        "H-FOYG",
        "2V-ZHM",
        "cross"
    ],
    [
        "H-FOYG",
        "A9-F18",
        "cross"
    ],
    [
        "OP7-BP",
        "B-7LYC",
        "cross"
    ],
    [
        "RZ3O-K",
        "0XN-SK",
        "cross"
    ],
    [
        "RZ3O-K",
        "4F9Y-3",
        "cross"
    ],
    [
        "TDP-T3",
        "MJ-5F9",
        "cross"
    ],
    [
        "U-3FKL",
        "9-ZA4Z",
        "cross"
    ],
    [
        "U-3FKL",
        "SY-OLX",
        "cross"
    ],
    [
        "XU7-CH",
        "H-HGGJ",
        "cross"
    ],
    [
        "01B-88",
        "0-U2M4",
        "internal"
    ],
    [
        "01B-88",
        "F18-AY",
        "internal"
    ],
    [
        "0FG-KS",
        "F-5WYK",
        "internal"
    ],
    [
        "0FG-KS",
        "RZ3O-K",
        "internal"
    ],
    [
        "1A8-6G",
        "PE-SAM",
        "internal"
    ],
    [
        "1A8-6G",
        "RY-2FX",
        "internal"
    ],
    [
        "2AUL-X",
        "PA-ALN",
        "internal"
    ],
    [
        "4-1ECP",
        "5-U12M",
        "internal"
    ],
    [
        "4-1ECP",
        "UYOC-1",
        "internal"
    ],
    [
        "4-M1TY",
        "K-3PQW",
        "internal"
    ],
    [
        "4F6-VZ",
        "3LL-O0",
        "internal"
    ],
    [
        "4F6-VZ",
        "L-POLO",
        "internal"
    ],
    [
        "4F9Y-3",
        "0XN-SK",
        "internal"
    ],
    [
        "5T-A3D",
        "5ZU-VG",
        "internal"
    ],
    [
        "5V-Q1R",
        "0XN-SK",
        "internal"
    ],
    [
        "5V-Q1R",
        "4F9Y-3",
        "internal"
    ],
    [
        "5V-Q1R",
        "MS-RXH",
        "internal"
    ],
    [
        "6-1T6Z",
        "5ZU-VG",
        "internal"
    ],
    [
        "6Q4-X6",
        "B9N2-2",
        "internal"
    ],
    [
        "6Q4-X6",
        "U4-V3J",
        "internal"
    ],
    [
        "7AH-SF",
        "4-1ECP",
        "internal"
    ],
    [
        "7AH-SF",
        "5-U12M",
        "internal"
    ],
    [
        "7AH-SF",
        "7MMJ-3",
        "internal"
    ],
    [
        "7AH-SF",
        "9-EXU9",
        "internal"
    ],
    [
        "7AH-SF",
        "UYOC-1",
        "internal"
    ],
    [
        "7JRA-G",
        "W-CSFY",
        "internal"
    ],
    [
        "7MMJ-3",
        "5-U12M",
        "internal"
    ],
    [
        "7MMJ-3",
        "9-EXU9",
        "internal"
    ],
    [
        "7MMJ-3",
        "PVF-N9",
        "internal"
    ],
    [
        "8B-A4E",
        "L-POLO",
        "internal"
    ],
    [
        "9-EXU9",
        "4-1ECP",
        "internal"
    ],
    [
        "9-EXU9",
        "PVF-N9",
        "internal"
    ],
    [
        "9-ZA4Z",
        "IU-E9T",
        "internal"
    ],
    [
        "9-ZA4Z",
        "NGM-OK",
        "internal"
    ],
    [
        "972C-1",
        "BEG-RL",
        "internal"
    ],
    [
        "972C-1",
        "U-W436",
        "internal"
    ],
    [
        "9IZ-HU",
        "2AUL-X",
        "internal"
    ],
    [
        "9IZ-HU",
        "F-HQWV",
        "internal"
    ],
    [
        "9IZ-HU",
        "OBV-YC",
        "internal"
    ],
    [
        "9WVY-F",
        "JZ-UQC",
        "internal"
    ],
    [
        "A1F-22",
        "3LL-O0",
        "internal"
    ],
    [
        "AK-L0Z",
        "2V-ZHM",
        "internal"
    ],
    [
        "B-7LYC",
        "49V-E4",
        "internal"
    ],
    [
        "B-7LYC",
        "PT-2KR",
        "internal"
    ],
    [
        "B-B0ME",
        "H-HGGJ",
        "internal"
    ],
    [
        "BEG-RL",
        "Z-ENUD",
        "internal"
    ],
    [
        "C6CG-W",
        "PE-SAM",
        "internal"
    ],
    [
        "D-QJR9",
        "B9N2-2",
        "internal"
    ],
    [
        "E-WMT7",
        "F-5WYK",
        "internal"
    ],
    [
        "E-WMT7",
        "FLK-LJ",
        "internal"
    ],
    [
        "EF-QZK",
        "F-5WYK",
        "internal"
    ],
    [
        "EH2I-P",
        "6-8QLA",
        "internal"
    ],
    [
        "EH2I-P",
        "R-AYGT",
        "internal"
    ],
    [
        "F-A3TR",
        "9IZ-HU",
        "internal"
    ],
    [
        "F-A3TR",
        "F-HQWV",
        "internal"
    ],
    [
        "F-A3TR",
        "OBV-YC",
        "internal"
    ],
    [
        "F18-AY",
        "RZ8A-P",
        "internal"
    ],
    [
        "FLK-LJ",
        "0FG-KS",
        "internal"
    ],
    [
        "G-GRSZ",
        "R-AYGT",
        "internal"
    ],
    [
        "H-29TM",
        "D-QJR9",
        "internal"
    ],
    [
        "H-FOYG",
        "1A8-6G",
        "internal"
    ],
    [
        "H-HGGJ",
        "A9-F18",
        "internal"
    ],
    [
        "HB-KSF",
        "6-1T6Z",
        "internal"
    ],
    [
        "IU-E9T",
        "O-QKSM",
        "internal"
    ],
    [
        "J9A-BH",
        "4F6-VZ",
        "internal"
    ],
    [
        "J9A-BH",
        "B-7LYC",
        "internal"
    ],
    [
        "J9A-BH",
        "PT-2KR",
        "internal"
    ],
    [
        "JM0A-4",
        "3LL-O0",
        "internal"
    ],
    [
        "JM0A-4",
        "4F6-VZ",
        "internal"
    ],
    [
        "JM0A-4",
        "A1F-22",
        "internal"
    ],
    [
        "JZ-UQC",
        "7M4-4C",
        "internal"
    ],
    [
        "K-3PQW",
        "C6CG-W",
        "internal"
    ],
    [
        "K-3PQW",
        "PE-SAM",
        "internal"
    ],
    [
        "K-3PQW",
        "RY-2FX",
        "internal"
    ],
    [
        "KOI8-Z",
        "D-QJR9",
        "internal"
    ],
    [
        "KOI8-Z",
        "H-29TM",
        "internal"
    ],
    [
        "LW-YEW",
        "5T-A3D",
        "internal"
    ],
    [
        "LW-YEW",
        "6-8QLA",
        "internal"
    ],
    [
        "LW-YEW",
        "EH2I-P",
        "internal"
    ],
    [
        "LW-YEW",
        "HB-KSF",
        "internal"
    ],
    [
        "M-SG47",
        "2-YO2K",
        "internal"
    ],
    [
        "M-SG47",
        "W-KXEX",
        "internal"
    ],
    [
        "M4-KX5",
        "0XN-SK",
        "internal"
    ],
    [
        "M4-KX5",
        "5V-Q1R",
        "internal"
    ],
    [
        "M5NO-B",
        "7M4-4C",
        "internal"
    ],
    [
        "M5NO-B",
        "JPEZ-R",
        "internal"
    ],
    [
        "MS-RXH",
        "U-3FKL",
        "internal"
    ],
    [
        "MTO2-2",
        "RZ8A-P",
        "internal"
    ],
    [
        "NGM-OK",
        "IU-E9T",
        "internal"
    ],
    [
        "NGM-OK",
        "O-QKSM",
        "internal"
    ],
    [
        "O-QKSM",
        "QKQ3-L",
        "internal"
    ],
    [
        "OBV-YC",
        "2AUL-X",
        "internal"
    ],
    [
        "OBV-YC",
        "F-HQWV",
        "internal"
    ],
    [
        "OJT-J3",
        "DE-IHK",
        "internal"
    ],
    [
        "OP7-BP",
        "5ZU-VG",
        "internal"
    ],
    [
        "OP7-BP",
        "EH2I-P",
        "internal"
    ],
    [
        "PFV-ZH",
        "L5Y4-M",
        "internal"
    ],
    [
        "PFV-ZH",
        "W-CSFY",
        "internal"
    ],
    [
        "PVF-N9",
        "5-U12M",
        "internal"
    ],
    [
        "QHY-RU",
        "2-YO2K",
        "internal"
    ],
    [
        "R-AG7W",
        "AY9X-Q",
        "internal"
    ],
    [
        "R-AG7W",
        "XU7-CH",
        "internal"
    ],
    [
        "RZ8A-P",
        "0-U2M4",
        "internal"
    ],
    [
        "RZ8A-P",
        "C3I-D5",
        "internal"
    ],
    [
        "SR-10Z",
        "2-YO2K",
        "internal"
    ],
    [
        "SR-10Z",
        "M-SG47",
        "internal"
    ],
    [
        "SR-10Z",
        "QHY-RU",
        "internal"
    ],
    [
        "SY-OLX",
        "7JRA-G",
        "internal"
    ],
    [
        "SY-OLX",
        "W-CSFY",
        "internal"
    ],
    [
        "SY-OLX",
        "XY-ZCI",
        "internal"
    ],
    [
        "TAL1-3",
        "2-YO2K",
        "internal"
    ],
    [
        "TAL1-3",
        "M-SG47",
        "internal"
    ],
    [
        "TAL1-3",
        "QHY-RU",
        "internal"
    ],
    [
        "TDP-T3",
        "B-B0ME",
        "internal"
    ],
    [
        "TDP-T3",
        "OJT-J3",
        "internal"
    ],
    [
        "U-3FKL",
        "4F9Y-3",
        "internal"
    ],
    [
        "U-W436",
        "JZ-UQC",
        "internal"
    ],
    [
        "U4-V3J",
        "H-29TM",
        "internal"
    ],
    [
        "V-3K7C",
        "2V-ZHM",
        "internal"
    ],
    [
        "VWES-Y",
        "QKQ3-L",
        "internal"
    ],
    [
        "XU7-CH",
        "2V-ZHM",
        "internal"
    ],
    [
        "XU7-CH",
        "AY9X-Q",
        "internal"
    ],
    [
        "Z-ENUD",
        "M5NO-B",
        "internal"
    ],
    [
        "Z-ENUD",
        "MJ-5F9",
        "internal"
    ],
    [
        "Z-ENUD",
        "U-W436",
        "internal"
    ],
    [
        "5T-A3D",
        "MTGF-2",
        "regional"
    ],
    [
        "AY9X-Q",
        "O8W-5O",
        "regional"
    ],
    [
        "B-B0ME",
        "QCGG-Q",
        "regional"
    ],
    [
        "BEG-RL",
        "Z-DRIY",
        "regional"
    ],
    [
        "C3I-D5",
        "Y-0HVF",
        "regional"
    ],
    [
        "E-WMT7",
        "EU-WFW",
        "regional"
    ],
    [
        "F-5WYK",
        "OTJ9-E",
        "regional"
    ],
    [
        "J9A-BH",
        "DYS-CG",
        "regional"
    ],
    [
        "MTO2-2",
        "HD-JVQ",
        "regional"
    ],
    [
        "PA-ALN",
        "EU-WFW",
        "regional"
    ],
    [
        "PA-ALN",
        "L-EUY2",
        "regional"
    ],
    [
        "PFV-ZH",
        "9S-GPT",
        "regional"
    ],
    [
        "PVF-N9",
        "QZ1-OH",
        "regional"
    ],
    [
        "R-AG7W",
        "IF-KD1",
        "regional"
    ],
    [
        "XY-ZCI",
        "QE2-FS",
        "regional"
    ]
]

# ===== Planetary Interaction =====
PI_DATA = {
    "3LL-O0": [
        {
            "planet_id": 40326876,
            "name": "3LL-O0 I",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326878,
            "name": "3LL-O0 II",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326880,
            "name": "3LL-O0 III",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40326884,
            "name": "3LL-O0 IV",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40326887,
            "name": "3LL-O0 V",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40326891,
            "name": "3LL-O0 VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326911,
            "name": "3LL-O0 VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326932,
            "name": "3LL-O0 VIII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326968,
            "name": "3LL-O0 IX",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        },
        {
            "planet_id": 40326971,
            "name": "3LL-O0 X",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326974,
            "name": "3LL-O0 XI",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "49V-E4": [
        {
            "planet_id": 40326799,
            "name": "49V-E4 I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326801,
            "name": "49V-E4 II",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326802,
            "name": "49V-E4 III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326803,
            "name": "49V-E4 IV",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        },
        {
            "planet_id": 40326805,
            "name": "49V-E4 V",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326818,
            "name": "49V-E4 VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326840,
            "name": "49V-E4 VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        }
    ],
    "4F6-VZ": [
        {
            "planet_id": 40326423,
            "name": "4F6-VZ I",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326424,
            "name": "4F6-VZ II",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326425,
            "name": "4F6-VZ III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326427,
            "name": "4F6-VZ IV",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326428,
            "name": "4F6-VZ V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326430,
            "name": "4F6-VZ VI",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40326434,
            "name": "4F6-VZ VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326444,
            "name": "4F6-VZ VIII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326449,
            "name": "4F6-VZ IX",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326468,
            "name": "4F6-VZ X",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        },
        {
            "planet_id": 40326472,
            "name": "4F6-VZ XI",
            "type_id": 12,
            "type": "Planet (Ice)"
        }
    ],
    "5T-A3D": [
        {
            "planet_id": 40323700,
            "name": "5T-A3D I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323701,
            "name": "5T-A3D II",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40323703,
            "name": "5T-A3D III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323706,
            "name": "5T-A3D IV",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323709,
            "name": "5T-A3D V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323711,
            "name": "5T-A3D VI",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        },
        {
            "planet_id": 40323713,
            "name": "5T-A3D VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323740,
            "name": "5T-A3D VIII",
            "type_id": 2063,
            "type": "Planet (Plasma)"
        },
        {
            "planet_id": 40323742,
            "name": "5T-A3D IX",
            "type_id": 13,
            "type": "Planet (Gas)"
        }
    ],
    "5ZU-VG": [
        {
            "planet_id": 40323408,
            "name": "5ZU-VG I",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40323410,
            "name": "5ZU-VG II",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40323412,
            "name": "5ZU-VG III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323413,
            "name": "5ZU-VG IV",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323419,
            "name": "5ZU-VG V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323424,
            "name": "5ZU-VG VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323443,
            "name": "5ZU-VG VII",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323447,
            "name": "5ZU-VG VIII",
            "type_id": 13,
            "type": "Planet (Gas)"
        }
    ],
    "6-1T6Z": [
        {
            "planet_id": 40323481,
            "name": "6-1T6Z I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323482,
            "name": "6-1T6Z II",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323484,
            "name": "6-1T6Z III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323486,
            "name": "6-1T6Z IV",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40323489,
            "name": "6-1T6Z V",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323502,
            "name": "6-1T6Z VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323511,
            "name": "6-1T6Z VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323522,
            "name": "6-1T6Z VIII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323559,
            "name": "6-1T6Z IX",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "6-8QLA": [
        {
            "planet_id": 40323616,
            "name": "6-8QLA I",
            "type_id": 2063,
            "type": "Planet (Plasma)"
        },
        {
            "planet_id": 40323618,
            "name": "6-8QLA II",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40323619,
            "name": "6-8QLA III",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        },
        {
            "planet_id": 40323621,
            "name": "6-8QLA IV",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323632,
            "name": "6-8QLA V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323635,
            "name": "6-8QLA VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323642,
            "name": "6-8QLA VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323668,
            "name": "6-8QLA VIII",
            "type_id": 13,
            "type": "Planet (Gas)"
        }
    ],
    "8B-A4E": [
        {
            "planet_id": 40326756,
            "name": "8B-A4E I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326758,
            "name": "8B-A4E II",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326760,
            "name": "8B-A4E III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326761,
            "name": "8B-A4E IV",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326762,
            "name": "8B-A4E V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326763,
            "name": "8B-A4E VI",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326765,
            "name": "8B-A4E VII",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326767,
            "name": "8B-A4E VIII",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326770,
            "name": "8B-A4E IX",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326776,
            "name": "8B-A4E X",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326780,
            "name": "8B-A4E XI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326788,
            "name": "8B-A4E XII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326795,
            "name": "8B-A4E XIII",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "A1F-22": [
        {
            "planet_id": 40326980,
            "name": "A1F-22 I",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326982,
            "name": "A1F-22 II",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326983,
            "name": "A1F-22 III",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40326984,
            "name": "A1F-22 IV",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326988,
            "name": "A1F-22 V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326991,
            "name": "A1F-22 VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40327006,
            "name": "A1F-22 VII",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "B-7LYC": [
        {
            "planet_id": 40326478,
            "name": "B-7LYC I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326479,
            "name": "B-7LYC II",
            "type_id": 2063,
            "type": "Planet (Plasma)"
        },
        {
            "planet_id": 40326481,
            "name": "B-7LYC III",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326484,
            "name": "B-7LYC IV",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326485,
            "name": "B-7LYC V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326486,
            "name": "B-7LYC VI",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40326489,
            "name": "B-7LYC VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326496,
            "name": "B-7LYC VIII",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40326501,
            "name": "B-7LYC IX",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326510,
            "name": "B-7LYC X",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        }
    ],
    "EH2I-P": [
        {
            "planet_id": 40323337,
            "name": "EH2I-P I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323338,
            "name": "EH2I-P II",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323340,
            "name": "EH2I-P III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323342,
            "name": "EH2I-P IV",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40323345,
            "name": "EH2I-P V",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40323347,
            "name": "EH2I-P VI",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323350,
            "name": "EH2I-P VII",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323354,
            "name": "EH2I-P VIII",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "G-GRSZ": [
        {
            "planet_id": 40323587,
            "name": "G-GRSZ I",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40323588,
            "name": "G-GRSZ II",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323590,
            "name": "G-GRSZ III",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323593,
            "name": "G-GRSZ IV",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323594,
            "name": "G-GRSZ V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323598,
            "name": "G-GRSZ VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323604,
            "name": "G-GRSZ VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323611,
            "name": "G-GRSZ VIII",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323614,
            "name": "G-GRSZ IX",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "HB-KSF": [
        {
            "planet_id": 40323255,
            "name": "HB-KSF I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323256,
            "name": "HB-KSF II",
            "type_id": 2063,
            "type": "Planet (Plasma)"
        },
        {
            "planet_id": 40323257,
            "name": "HB-KSF III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323259,
            "name": "HB-KSF IV",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323262,
            "name": "HB-KSF V",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323281,
            "name": "HB-KSF VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323300,
            "name": "HB-KSF VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323324,
            "name": "HB-KSF VIII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323330,
            "name": "HB-KSF IX",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40323333,
            "name": "HB-KSF X",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "J9A-BH": [
        {
            "planet_id": 40326354,
            "name": "J9A-BH I",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40326356,
            "name": "J9A-BH II",
            "type_id": 2063,
            "type": "Planet (Plasma)"
        },
        {
            "planet_id": 40326358,
            "name": "J9A-BH III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326360,
            "name": "J9A-BH IV",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326362,
            "name": "J9A-BH V",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326378,
            "name": "J9A-BH VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326383,
            "name": "J9A-BH VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326414,
            "name": "J9A-BH VIII",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        },
        {
            "planet_id": 40326417,
            "name": "J9A-BH IX",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "JM0A-4": [
        {
            "planet_id": 40326514,
            "name": "JM0A-4 I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326516,
            "name": "JM0A-4 II",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40326518,
            "name": "JM0A-4 III",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        },
        {
            "planet_id": 40326521,
            "name": "JM0A-4 IV",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40326523,
            "name": "JM0A-4 V",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326547,
            "name": "JM0A-4 VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326573,
            "name": "JM0A-4 VII",
            "type_id": 12,
            "type": "Planet (Ice)"
        },
        {
            "planet_id": 40326577,
            "name": "JM0A-4 VIII",
            "type_id": 2016,
            "type": "Planet (Barren)"
        }
    ],
    "L-POLO": [
        {
            "planet_id": 40326667,
            "name": "L-POLO I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326668,
            "name": "L-POLO II",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326670,
            "name": "L-POLO III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326671,
            "name": "L-POLO IV",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326690,
            "name": "L-POLO V",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326692,
            "name": "L-POLO VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326722,
            "name": "L-POLO VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326744,
            "name": "L-POLO VIII",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326750,
            "name": "L-POLO IX",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        }
    ],
    "LW-YEW": [
        {
            "planet_id": 40323190,
            "name": "LW-YEW I",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323192,
            "name": "LW-YEW II",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323197,
            "name": "LW-YEW III",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40323201,
            "name": "LW-YEW IV",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323205,
            "name": "LW-YEW V",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323226,
            "name": "LW-YEW VI",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323248,
            "name": "LW-YEW VII",
            "type_id": 13,
            "type": "Planet (Gas)"
        }
    ],
    "OP7-BP": [
        {
            "planet_id": 40323359,
            "name": "OP7-BP I",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40323361,
            "name": "OP7-BP II",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323363,
            "name": "OP7-BP III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323365,
            "name": "OP7-BP IV",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40323368,
            "name": "OP7-BP V",
            "type_id": 2017,
            "type": "Planet (Storm)"
        },
        {
            "planet_id": 40323370,
            "name": "OP7-BP VI",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        },
        {
            "planet_id": 40323372,
            "name": "OP7-BP VII",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323375,
            "name": "OP7-BP VIII",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323378,
            "name": "OP7-BP IX",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323402,
            "name": "OP7-BP X",
            "type_id": 2014,
            "type": "Planet (Oceanic)"
        }
    ],
    "PT-2KR": [
        {
            "planet_id": 40326581,
            "name": "PT-2KR I",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326583,
            "name": "PT-2KR II",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40326585,
            "name": "PT-2KR III",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40326586,
            "name": "PT-2KR IV",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326606,
            "name": "PT-2KR V",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40326632,
            "name": "PT-2KR VI",
            "type_id": 12,
            "type": "Planet (Ice)"
        }
    ],
    "R-AYGT": [
        {
            "planet_id": 40323564,
            "name": "R-AYGT I",
            "type_id": 2015,
            "type": "Planet (Lava)"
        },
        {
            "planet_id": 40323565,
            "name": "R-AYGT II",
            "type_id": 11,
            "type": "Planet (Temperate)"
        },
        {
            "planet_id": 40323568,
            "name": "R-AYGT III",
            "type_id": 2016,
            "type": "Planet (Barren)"
        },
        {
            "planet_id": 40323572,
            "name": "R-AYGT IV",
            "type_id": 13,
            "type": "Planet (Gas)"
        },
        {
            "planet_id": 40323580,
            "name": "R-AYGT V",
            "type_id": 13,
            "type": "Planet (Gas)"
        }
    ]
}
